//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface   : NSObject
{
}

+ (id)convertToJsonFromDict:(id)arg1;
+ (id)convertToDictFromStr:(id)arg1;
+ (void)writeToStorageWithKey:(id)arg1 andValue:(id)arg2;
+ (void)reset;

@end

