//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class NSString, UIActivityIndicatorView, UIImageView;

@interface  8 : CDVPlugin
{
    UIActivityIndicatorView *_activityView;
    UIImageView *_imageView;
    NSString *_curImageName;
    _Bool _visible;
    _Bool _destroyed;
}

- (void).cxx_destruct;
- (void)setVisible:(_Bool)arg1 andForce:(_Bool)arg2;
- (void)setVisible:(_Bool)arg1;
- (void)updateBounds;
- (void)updateImage;
- (long long)getCurrentOrientation;
- (id)getImageName:(long long)arg1 delegate:(id)arg2 device:(CDStruct_e38957e0)arg3;
- (CDStruct_e38957e0)getCurrentDevice;
- (void)destroyViews;
- (void)hideViews;
- (void)createViews;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)pageDidLoad;
- (void)hide:(id)arg1;
- (void)show:(id)arg1;
- (void)pluginInitialize;

@end

