//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AppDelegate.h"

@class NSDictionary;

@interface AppDelegate (APPLocalNotification)
+ (void)load;
- (void)dealloc;
@property(retain, nonatomic) NSDictionary *localNotification;
- (void)postProcessLocalNotificationOnApplicationDidBecomeActive:(id)arg1 withNotification:(id)arg2;
- (void)localNotificationOnApplicationDidBecomeActive:(id)arg1;
- (void)createLocalNotificationChecker:(id)arg1;
- (id)swizzled_pluginInitialize;
- (id)getCommandInstance:(id)arg1;
@end

