//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVAppDelegate.h"

#import "WCSessionDelegate.h"

@class NSString, WCSession;

@interface AppDelegate : CDVAppDelegate <WCSessionDelegate>
{
    _Bool _isPairedWatchExist;
    WCSession *_session;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isPairedWatchExist; // @synthesize isPairedWatchExist=_isPairedWatchExist;
@property(retain, nonatomic) WCSession *session; // @synthesize session=_session;
- (void)session:(id)arg1 activationDidCompleteWithState:(long long)arg2 error:(id)arg3;
- (void)sessionDidDeactivate:(id)arg1;
- (void)checkPairedWatches;
- (void)dealloc;
- (void)userDidTakeScreenshot;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)wlInitDidFailWithResult:(id)arg1;
- (void)wlInitWebFrameworkDidCompleteWithResult:(id)arg1;
- (void)session:(id)arg1 didReceiveMessage:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

