//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AppDelegate.h"

@class NSDictionary, NSNumber;

@interface AppDelegate (notification)
+ (void)load;
- (void)dealloc;
@property(retain, nonatomic) NSNumber *coldstart;
@property(retain, nonatomic) NSDictionary *launchNotification;
- (void)application:(id)arg1 handleActionWithIdentifier:(id)arg2 forRemoteNotification:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)postProcessPushPluginOnApplicationDidBecomeActive:(id)arg1 withNotification:(id)arg2;
- (void)pushPluginOnApplicationDidBecomeActive:(id)arg1;
- (_Bool)userHasRemoteNotificationsEnabled;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)createNotificationChecker:(id)arg1;
- (id)pushPluginSwizzledInit;
- (id)getCommandInstance:(id)arg1;
@end

