//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AppDelegate.h"

@interface AppDelegate (APPAppEvent)
+ (void)exchange_methods:(SEL)arg1 swizzled:(SEL)arg2;
+ (void)load;
- (void)postNotificationName:(id)arg1 object:(id)arg2;
- (void)swizzled_application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)swizzled_application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
@end

