//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDictionary, NSNumber, NSString;

@interface APPLocalNotificationOptions9 : NSObject
{
    NSDictionary *dict;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *dict; // @synthesize dict;
- (_Bool)stringIsNullOrEmpty:(id)arg1;
- (id)soundNameForResource:(id)arg1;
- (id)soundNameForAsset:(id)arg1;
- (_Bool)isRepeating;
@property(readonly, getter=userInfo) NSDictionary *userInfo;
@property(readonly, getter=repeatInterval) unsigned long long repeatInterval;
@property(readonly, getter=fireDate) NSDate *fireDate;
@property(readonly, getter=soundName) NSString *soundName;
@property(readonly, getter=alertBody) NSString *alertBody;
@property(readonly, getter=badgeNumber) long long badgeNumber;
- (id)text;
- (id)title;
@property(readonly, getter=id) NSNumber *id;
- (id)initWithDict:(id)arg1;

@end

