//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSNumber, NSString, UNNotificationSound;

@interface APPLocalNotificationOptions : NSObject
{
    NSDictionary *dict;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *dict; // @synthesize dict;
- (_Bool)stringIsNullOrEmpty:(id)arg1;
- (id)soundNameForResource:(id)arg1;
- (id)soundNameForAsset:(id)arg1;
- (unsigned long long)repeatInterval;
- (double)timeInterval;
- (id)triggerWithDateMatchingComponents;
- (id)triggerWithTimeInterval;
@property(readonly, getter=userInfo) NSDictionary *userInfo;
- (id)trigger;
- (_Bool)isRepeating;
- (id)fireDate;
@property(readonly, getter=sound) UNNotificationSound *sound;
@property(readonly, getter=badge) NSNumber *badge;
@property(readonly, getter=text) NSString *text;
@property(readonly, getter=subtitle) NSString *subtitle;
@property(readonly, getter=title) NSString *title;
@property(readonly, getter=identifier) NSString *identifier;
@property(readonly, getter=id) NSNumber *id;
- (id)initWithDict:(id)arg1;

@end

