//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

#import "UNUserNotificationCenterDelegate.h"

@class CDVInvokedUrlCommand, NSDictionary, NSMutableArray, NSString, UIApplication, UNUserNotificationCenter;

@interface APPLocalNotification : CDVPlugin <UNUserNotificationCenterDelegate>
{
    _Bool deviceready;
    NSMutableArray *eventQueue;
    NSDictionary *_localNotification;
    CDVInvokedUrlCommand *_command;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CDVInvokedUrlCommand *command; // @synthesize command=_command;
@property(retain, nonatomic) NSDictionary *localNotification; // @synthesize localNotification=_localNotification;
@property(readonly, retain, nonatomic) NSMutableArray *eventQueue; // @synthesize eventQueue;
@property _Bool deviceready; // @synthesize deviceready;
- (void)fireEvent:(id)arg1 localnotification:(id)arg2;
- (void)onAppTerminate;
- (void)didRegisterUserNotificationSettings:(id)arg1;
- (void)didFinishLaunchingWithOptions:(id)arg1;
- (void)didReceiveLocalNotification:(id)arg1;
- (void)didReceiveLocalNotification;
- (void)cancelAllNotificationsWhichAreOlderThen:(float)arg1;
- (void)cancelForerunnerLocalNotification:(id)arg1;
- (void)updateLocalNotification:(id)arg1 withOptions:(id)arg2;
- (void)scheduleLocalNotification:(id)arg1;
- (void)fireEvent:(id)arg1 notification:(id)arg2;
- (void)fireEvent:(id)arg1;
@property(readonly, getter=center) UNUserNotificationCenter *center;
@property(readonly, getter=app) UIApplication *app;
- (void)execCallback:(id)arg1;
- (id)applicationState;
- (void)pluginInitialize;
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)clearAllNotifications;
- (void)cancelAllNotifications;
- (void)updateNotification:(id)arg1 withOptions:(id)arg2;
- (void)scheduleNotification:(id)arg1;
- (void)registerPermission:(id)arg1;
- (void)hasPermission:(id)arg1;
- (void)getOptions:(id)arg1 byType:(unsigned long long)arg2;
- (void)getOption:(id)arg1 byType:(unsigned long long)arg2;
- (void)getTriggered:(id)arg1;
- (void)getScheduled:(id)arg1;
- (void)getAll:(id)arg1;
- (void)getSingleTriggered:(id)arg1;
- (void)getSingleScheduled:(id)arg1;
- (void)getSingle:(id)arg1;
- (void)getIds:(id)arg1 byType:(unsigned long long)arg2;
- (void)getTriggeredIds:(id)arg1;
- (void)getScheduledIds:(id)arg1;
- (void)getAllIds:(id)arg1;
- (void)isPresent:(id)arg1 type:(unsigned long long)arg2;
- (void)isTriggered:(id)arg1;
- (void)isScheduled:(id)arg1;
- (void)isPresent:(id)arg1;
- (void)clearAll:(id)arg1;
- (void)clear:(id)arg1;
- (void)cancelAll:(id)arg1;
- (void)cancel:(id)arg1;
- (void)update:(id)arg1;
- (void)doSchedule:(id)arg1;
- (void)schedule:(id)arg1;
- (void)deviceready:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

