//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface Brightness : CDVPlugin
{
}

- (void)setKeepScreenOn:(id)arg1;
- (void)setBrightness:(id)arg1;
- (void)getBrightness:(id)arg1;

@end

