//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

#import "FocusDelegate.h"
#import "TakePictureDelegate.h"

@class CameraRenderController, CameraSessionManager, NSString;

@interface CameraPreview : CDVPlugin <TakePictureDelegate, FocusDelegate>
{
    _Bool _storeToFile;
    CameraSessionManager *_sessionManager;
    CameraRenderController *_cameraRenderController;
    NSString *_onPictureTakenHandlerId;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool storeToFile; // @synthesize storeToFile=_storeToFile;
@property(retain, nonatomic) NSString *onPictureTakenHandlerId; // @synthesize onPictureTakenHandlerId=_onPictureTakenHandlerId;
@property(retain, nonatomic) CameraRenderController *cameraRenderController; // @synthesize cameraRenderController=_cameraRenderController;
@property(retain, nonatomic) CameraSessionManager *sessionManager; // @synthesize sessionManager=_sessionManager;
- (id)getTempFilePath:(id)arg1;
- (id)getTempDirectoryPath;
- (void)invokeTakePicture:(double)arg1 withHeight:(double)arg2 withQuality:(double)arg3;
- (void)invokeTakePictureOnFocus;
- (void)invokeTakePicture;
- (void)invokeTapToFocus:(struct CGPoint)arg1;
- (struct CGImage *)CGImageRotated:(struct CGImage *)arg1 withRadians:(double)arg2;
- (double)radiansFromUIImageOrientation:(long long)arg1;
- (void)tapToFocus:(id)arg1;
- (id)getBase64Image:(struct CGImage *)arg1 withQuality:(double)arg2;
- (void)getSupportedPictureSizes:(id)arg1;
- (void)setPreviewSize:(id)arg1;
- (void)setColorEffect:(id)arg1;
- (void)takeSnapshot:(id)arg1;
- (void)takePicture:(id)arg1;
- (void)setExposureCompensation:(id)arg1;
- (void)getExposureCompensation:(id)arg1;
- (void)getExposureCompensationRange:(id)arg1;
- (void)setWhiteBalanceMode:(id)arg1;
- (void)getWhiteBalanceMode:(id)arg1;
- (void)getSupportedWhiteBalanceModes:(id)arg1;
- (void)setExposureMode:(id)arg1;
- (void)getExposureMode:(id)arg1;
- (void)getExposureModes:(id)arg1;
- (void)getMaxZoom:(id)arg1;
- (void)getHorizontalFOV:(id)arg1;
- (void)getZoom:(id)arg1;
- (void)setZoom:(id)arg1;
- (void)setFlashMode:(id)arg1;
- (void)getFlashMode:(id)arg1;
- (void)getSupportedFlashModes:(id)arg1;
- (void)setFocusMode:(id)arg1;
- (void)getFocusMode:(id)arg1;
- (void)getSupportedFocusModes:(id)arg1;
- (void)switchCamera:(id)arg1;
- (void)showCamera:(id)arg1;
- (void)hideCamera:(id)arg1;
- (void)stopCamera:(id)arg1;
- (void)startCamera:(id)arg1;
- (void)pluginInitialize;

@end

