//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"
#import "OnFocusDelegate.h"

@class CIContext, CIImage, CameraSessionManager, EAGLContext, NSLock, NSString;

@interface CameraRenderController : UIViewController <AVCaptureVideoDataOutputSampleBufferDelegate, OnFocusDelegate>
{
    unsigned int _renderBuffer;
    struct __CVOpenGLESTextureCache *_videoTextureCache;
    struct __CVBuffer *_lumaTexture;
    _Bool _dragEnabled;
    _Bool _tapToTakePicture;
    _Bool _tapToFocus;
    EAGLContext *_context;
    id delegate;
    CameraSessionManager *_sessionManager;
    CIContext *_ciContext;
    CIImage *_latestFrame;
    NSLock *_renderLock;
}

- (void).cxx_destruct;
@property _Bool tapToFocus; // @synthesize tapToFocus=_tapToFocus;
@property _Bool tapToTakePicture; // @synthesize tapToTakePicture=_tapToTakePicture;
@property _Bool dragEnabled; // @synthesize dragEnabled=_dragEnabled;
@property(retain, nonatomic) NSLock *renderLock; // @synthesize renderLock=_renderLock;
@property(retain, nonatomic) CIImage *latestFrame; // @synthesize latestFrame=_latestFrame;
@property(retain, nonatomic) CIContext *ciContext; // @synthesize ciContext=_ciContext;
@property(retain, nonatomic) CameraSessionManager *sessionManager; // @synthesize sessionManager=_sessionManager;
@property(nonatomic) id delegate; // @synthesize delegate;
@property(retain, nonatomic) EAGLContext *context; // @synthesize context=_context;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)shouldAutorotate;
- (void)didReceiveMemoryWarning;
- (void)viewDidUnload;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)applicationEnteredForeground:(id)arg1;
- (void)appplicationIsActive:(id)arg1;
- (void)handlePan:(id)arg1;
- (void)onFocus;
- (void)handleFocusTap:(id)arg1;
- (void)handleTakePictureTap:(id)arg1;
- (void)handleFocusAndTakePictureTap:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

