//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVCaptureDevice, AVCaptureDeviceInput, AVCaptureSession, AVCaptureStillImageOutput, AVCaptureVideoDataOutput, CIFilter, NSDictionary, NSLock, NSObject<OS_dispatch_queue>, NSString;

@interface CameraSessionManager : NSObject
{
    CIFilter *_ciFilter;
    NSLock *_filterLock;
    AVCaptureSession *_session;
    NSObject<OS_dispatch_queue> *_sessionQueue;
    long long _defaultCamera;
    long long _defaultFlashMode;
    double _videoZoomFactor;
    AVCaptureDevice *_device;
    AVCaptureDeviceInput *_videoDeviceInput;
    AVCaptureStillImageOutput *_stillImageOutput;
    AVCaptureVideoDataOutput *_dataOutput;
    id _delegate;
    NSString *_currentWhiteBalanceMode;
    NSDictionary *_colorTemperatures;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *colorTemperatures; // @synthesize colorTemperatures=_colorTemperatures;
@property(retain, nonatomic) NSString *currentWhiteBalanceMode; // @synthesize currentWhiteBalanceMode=_currentWhiteBalanceMode;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AVCaptureVideoDataOutput *dataOutput; // @synthesize dataOutput=_dataOutput;
@property(retain, nonatomic) AVCaptureStillImageOutput *stillImageOutput; // @synthesize stillImageOutput=_stillImageOutput;
@property(retain, nonatomic) AVCaptureDeviceInput *videoDeviceInput; // @synthesize videoDeviceInput=_videoDeviceInput;
@property(retain, nonatomic) AVCaptureDevice *device; // @synthesize device=_device;
@property(nonatomic) double videoZoomFactor; // @synthesize videoZoomFactor=_videoZoomFactor;
@property(nonatomic) long long defaultFlashMode; // @synthesize defaultFlashMode=_defaultFlashMode;
@property(nonatomic) long long defaultCamera; // @synthesize defaultCamera=_defaultCamera;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *sessionQueue; // @synthesize sessionQueue=_sessionQueue;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(retain, nonatomic) NSLock *filterLock; // @synthesize filterLock=_filterLock;
@property(retain) CIFilter *ciFilter; // @synthesize ciFilter=_ciFilter;
- (id)cameraWithPosition:(long long)arg1;
- (void)checkDeviceAuthorizationStatus;
- (void)tapToFocus:(double)arg1 yPoint:(double)arg2;
- (void)takePictureOnFocus;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)setWhiteBalanceMode:(id)arg1;
- (id)getWhiteBalanceMode;
- (id)getSupportedWhiteBalanceModes;
- (void)setExposureCompensation:(double)arg1;
- (double)getExposureCompensation;
- (id)getExposureCompensationRange;
- (id)setExposureMode:(id)arg1;
- (id)getExposureMode;
- (id)getExposureModes;
- (double)getMaxZoom;
- (float)getHorizontalFOV;
- (double)getZoom;
- (void)setZoom:(double)arg1;
- (void)setTorchMode;
- (void)setFlashMode:(long long)arg1;
- (long long)getFlashMode;
- (id)getFlashModes;
- (id)setFocusMode:(id)arg1;
- (id)getFocusMode;
- (id)getFocusModes;
- (void)switchCamera:(CDUnknownBlockType)arg1;
- (void)updateOrientation:(long long)arg1;
- (void)setupSession:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (long long)getCurrentOrientation:(long long)arg1;
- (long long)getCurrentOrientation;
- (id)getDeviceFormats;
- (id)init;

@end

