//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_CCTClearcutCounters;

@protocol CCTClearcutAutoCountersDelegate <NSObject>
- (long long)maxCounterCount;
- (_Bool)shouldLogCounters;
- (void)logCounters:(MLKITx_CCTClearcutCounters *)arg1;
@end

