//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_CCTClearcutLogEvent;

@protocol CCTClearcutLogTransformer <NSObject>
- (MLKITx_CCTClearcutLogEvent *)transform:(MLKITx_CCTClearcutLogEvent *)arg1;
@end

