//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_CCTLogContext, MLKITx_CCTLogFile, NSArray, NSError, NSHTTPURLResponse, NSURLRequest;

@protocol CCTClearcutMetaLoggerProtocol <NSObject>
- (void)logUploadTime:(long long)arg1 endTime:(long long)arg2 error:(NSError *)arg3;
- (void)logDeletingOverTTLLogFiles:(NSArray *)arg1;
- (void)logDeletingOverSizeLogFiles:(NSArray *)arg1;
- (void)logRequestUploadDelayWithCurrentTime:(long long)arg1 logFile:(MLKITx_CCTLogFile *)arg2;
- (void)logResponse:(NSHTTPURLResponse *)arg1 context:(MLKITx_CCTLogContext *)arg2 startTime:(long long)arg3 finishTime:(long long)arg4;
- (void)logRequestContentLength:(MLKITx_CCTLogContext *)arg1 request:(NSURLRequest *)arg2;
- (void)logFilesWillBeUploaded:(NSArray *)arg1;
@end

