//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GPBMessage, NSData, NSOutputStream, NSString;

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct AudioBuffer {
    unsigned int _field1;
    unsigned int _field2;
    void *_field3;
};

struct AudioBufferList {
    unsigned int _field1;
    struct AudioBuffer _field2[1];
};

struct AudioStreamBasicDescription {
    double mSampleRate;
    unsigned int mFormatID;
    unsigned int mFormatFlags;
    unsigned int mBytesPerPacket;
    unsigned int mFramesPerPacket;
    unsigned int mBytesPerFrame;
    unsigned int mChannelsPerFrame;
    unsigned int mBitsPerChannel;
    unsigned int mReserved;
};

struct AudioTimeStamp {
    double _field1;
    unsigned long long _field2;
    double _field3;
    unsigned long long _field4;
    struct SMPTETime _field5;
    unsigned int _field6;
    unsigned int _field7;
};

struct CATransform3D {
    double m11;
    double m12;
    double m13;
    double m14;
    double m21;
    double m22;
    double m23;
    double m24;
    double m31;
    double m32;
    double m33;
    double m34;
    double m41;
    double m42;
    double m43;
    double m44;
};

struct CC_SHA256state_st {
    unsigned int count[2];
    unsigned int hash[8];
    unsigned int wbuf[16];
};

struct CGAffineTransform {
    double a;
    double b;
    double c;
    double d;
    double tx;
    double ty;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct GPBCodedInputStreamState {
    char *bytes;
    unsigned long long bufferSize;
    unsigned long long bufferPos;
    unsigned long long currentLimit;
    int lastTag;
    unsigned long long recursionDepth;
};

struct GPBExtensionDescription {
    CDUnion_88782d86 _field1;
    char *_field2;
    char *_field3;
    char *_field4;
    CDUnknownFunctionPointerType _field5;
    int _field6;
    unsigned char _field7;
    unsigned char _field8;
};

struct GPBExtensionRange {
    unsigned int _field1;
    unsigned int _field2;
};

struct GPBMessageFieldDescription {
    char *_field1;
    union {
        char *_field1;
        CDUnknownFunctionPointerType _field2;
        CDUnknownFunctionPointerType _field3;
    } _field2;
    unsigned int _field3;
    int _field4;
    unsigned int _field5;
    unsigned short _field6;
    unsigned char _field7;
};

struct GPBMessage_Storage {
    unsigned int _field1[0];
};

struct GPBOutputBufferState {
    char *bytes;
    unsigned long long size;
    unsigned long long position;
    NSOutputStream *output;
};

struct GPUByteColorVector {
    unsigned char _field1;
    unsigned char _field2;
    unsigned char _field3;
    unsigned char _field4;
};

struct GPUMatrix3x3 {
    struct GPUVector3 one;
    struct GPUVector3 two;
    struct GPUVector3 three;
};

struct GPUMatrix4x4 {
    struct GPUVector4 one;
    struct GPUVector4 two;
    struct GPUVector4 three;
    struct GPUVector4 four;
};

struct GPUTextureOptions {
    unsigned int minFilter;
    unsigned int magFilter;
    unsigned int wrapS;
    unsigned int wrapT;
    unsigned int internalFormat;
    unsigned int format;
    unsigned int type;
};

struct GPUVector3 {
    float one;
    float two;
    float three;
};

struct GPUVector4 {
    float one;
    float two;
    float three;
    float four;
};

struct LineBox;

struct LmiAllocatorS_ {
    CDUnknownFunctionPointerType _field1;
    CDUnknownFunctionPointerType _field2;
    unsigned long long _field3;
    void *_field4;
};

struct LmiAudioBufferDebugInfo_ {
    CDStruct_890fc611 name;
    long long bufferSize;
    long long lowestThreshold;
    long long lowThreshold;
    long long highThreshold;
    long long highestThreshold;
    long long maxThreshold;
    long long played;
    long long underrun;
    long long overrun;
};

struct LmiAudioCapturer_ {
    struct _opaque_pthread_mutex_t _field1;
    struct LmiAllocatorS_ *_field2;
    CDStruct_890fc611 _field3;
    CDStruct_890fc611 _field4;
    CDStruct_890fc611 _field5;
    CDStruct_890fc611 _field6;
    CDStruct_890fc611 _field7;
    unsigned char _field8;
    int _field9;
    CDUnknownFunctionPointerType _field10;
    CDUnknownFunctionPointerType _field11;
    void *_field12;
    unsigned int _field13;
    struct LmiThread_ _field14;
    void *_field15;
    unsigned int _field16;
    unsigned char _field17;
    unsigned int _field18;
    unsigned int _field19;
    unsigned int _field20;
    unsigned int _field21;
    unsigned int _field22;
    unsigned int _field23;
    unsigned int _field24;
    struct LmiPcmFrame_ *_field25;
    unsigned int _field26;
    unsigned int _field27;
    int _field28;
    CDStruct_c0454aff _field29;
    long long _field30;
    CDStruct_4fd828e1 _field31;
    CDStruct_83113961 _field32;
    long long _field33;
    long long _field34;
    unsigned int _field35;
    unsigned int _field36;
    unsigned char _field37;
    struct {
        int _field1;
        unsigned char _field2;
        CDUnknownFunctionPointerType _field3;
        CDUnknownFunctionPointerType _field4;
    } _field38[2];
    unsigned char _field39;
    unsigned char _field40;
};

struct LmiAudioEnhMixer_;

struct LmiAudioPlaybackDevice_ {
    CDStruct_890fc611 _field1;
    CDStruct_890fc611 _field2;
    CDStruct_890fc611 _field3;
    CDStruct_890fc611 _field4;
    CDStruct_890fc611 _field5;
    void *_field6;
    struct _opaque_pthread_mutex_t _field7;
    struct LmiAllocatorS_ *_field8;
    unsigned char _field9;
    int _field10;
    struct LmiVector_LmiVoidPtr _field11;
    void *_field12;
    struct LmiThread_ _field13;
    unsigned char _field14;
    unsigned int _field15;
    unsigned int _field16;
    unsigned int _field17;
    unsigned int _field18;
    short **_field19;
    CDStruct_ecc2bd45 _field20;
    CDUnknownFunctionPointerType _field21;
    int _field22;
    CDStruct_4fd828e1 _field23;
    long long _field24;
    long long _field25;
    unsigned int _field26;
    unsigned int _field27;
    unsigned char _field28;
    unsigned char _field29;
    struct LmiAudioEnhMixer_ *_field30;
};

struct LmiListNodeBase__LmiVoidPtr {
    union LmiListNodePtr__LmiVoidPtr _field1;
    union LmiListNodePtr__LmiVoidPtr _field2;
};

struct LmiListNode__LmiVoidPtr;

struct LmiPcmFrame_;

struct LmiScreenManager_ {
    struct LmiVector_LmiScreen _field1;
    CDUnknownFunctionPointerType _field2;
    CDUnknownFunctionPointerType _field3;
    CDUnknownFunctionPointerType _field4;
    void *_field5;
    struct LmiAllocatorS_ *_field6;
    struct _opaque_pthread_mutex_t _field7;
    struct _opaque_pthread_mutex_t _field8;
    int _field9;
    void *_field10;
};

struct LmiScreen_;

struct LmiThread_ {
    struct {
        char _field1[32];
        int _field2;
        unsigned long long _field3;
        CDUnknownFunctionPointerType _field4;
        void *_field5;
        void *_field6;
        int _field7;
    } _field1;
    struct _opaque_pthread_attr_t {
        long long _field1;
        char _field2[56];
    } _field2;
    struct _opaque_pthread_t *_field3;
};

struct LmiVector_LmiLabel {
    struct LmiAllocatorS_ *_field1;
    CDStruct_183601bc *_field2;
    CDStruct_183601bc *_field3;
    CDStruct_183601bc *_field4;
};

struct LmiVector_LmiScreen {
    struct LmiAllocatorS_ *_field1;
    struct LmiScreen_ *_field2;
    struct LmiScreen_ *_field3;
    struct LmiScreen_ *_field4;
};

struct LmiVector_LmiVideoCapturerCapability {
    struct LmiAllocatorS_ *_field1;
    CDStruct_183601bc *_field2;
    CDStruct_183601bc *_field3;
    CDStruct_183601bc *_field4;
};

struct LmiVector_LmiVoidPtr {
    struct LmiAllocatorS_ *_field1;
    void **_field2;
    void **_field3;
    void **_field4;
};

struct LmiVideoCapturer_ {
    struct _opaque_pthread_mutex_t _field1;
    struct _opaque_pthread_mutex_t _field2;
    int _field3;
    unsigned char _field4;
    unsigned char _field5;
    unsigned char _field6;
    unsigned char _field7;
    CDStruct_890fc611 _field8;
    CDStruct_890fc611 _field9;
    CDStruct_890fc611 _field10;
    int _field11;
    struct LmiVector_LmiVideoCapturerCapability _field12;
    void *_field13;
    struct LmiAllocatorS_ *_field14;
    CDUnknownFunctionPointerType _field15;
    void *_field16;
    CDUnknownFunctionPointerType _field17;
    void *_field18;
    CDUnknownFunctionPointerType _field19;
    void *_field20;
    struct {
        unsigned int _field1;
        int _field2;
        int _field3;
        long long _field4;
    } _field21;
    unsigned char _field22;
};

struct LmiWindow_ {
    struct LmiAllocatorS_ *_field1;
    void *_field2;
    void *_field3;
    CDStruct_a734b2e2 _field4;
    CDStruct_a734b2e2 _field5;
    int _field6;
    struct _opaque_pthread_mutex_t _field7;
    struct _opaque_pthread_mutex_t _field8;
    CDStruct_c0454aff _field9;
    CDStruct_c0454aff _field10;
    struct LmiThread_ _field11;
    unsigned char _field12;
    struct {
        unsigned char _field1;
        unsigned char _field2;
        unsigned char _field3;
    } _field13;
    CDStruct_632cb68a _field14;
    struct {
        struct LmiYuv420Image_ _field1;
        long long _field2;
        unsigned int _field3;
        unsigned int _field4;
        unsigned char _field5;
        unsigned char _field6;
    } _field15;
    CDStruct_a734b2e2 _field16;
    unsigned char _field17;
    unsigned int _field18;
    unsigned int _field19;
    int _field20;
    unsigned char _field21;
    unsigned char _field22;
    unsigned char _field23;
    unsigned char _field24;
    int _field25;
    int _field26;
    int _field27;
    int _field28;
    int _field29;
    int _field30;
    unsigned int _field31;
    struct LmiVector_LmiVoidPtr _field32;
    struct LmiWindow_ *_field33;
    int _field34;
    struct _opaque_pthread_mutex_t _field35;
    struct LmiVector_LmiLabel _field36;
    int _field37;
    CDUnknownFunctionPointerType _field38;
    void *_field39;
    int _field40;
    void *_field41;
    unsigned char _field42;
    unsigned int _field43;
    void *_field44;
    unsigned long long _field45;
    CDUnknownFunctionPointerType _field46;
    unsigned int _field47;
    int _field48;
    struct LmiYuv420Image_ _field49;
    struct LmiYuv420Image_ _field50;
    CDStruct_890fc611 _field51;
};

struct LmiYuv420Image_ {
    struct {
        CDStruct_183601bc *_field1;
        void *_field2;
    } _field1[3];
};

struct MLKITx_SRLMemoizingScopeIvars;

struct MLKITx_SRLRegistryIvars;

struct MLKITx__SRLBindingsRegistrationData;

struct SMPTETime {
    short _field1;
    short _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    short _field6;
    short _field7;
    short _field8;
    short _field9;
};

struct SRDelegateAvailableMethods {
    unsigned int didReceiveMessage:1;
    unsigned int didReceiveMessageWithString:1;
    unsigned int didReceiveMessageWithData:1;
    unsigned int didOpen:1;
    unsigned int didFailWithError:1;
    unsigned int didCloseWithCode:1;
    unsigned int didReceivePong:1;
    unsigned int shouldConvertTextFrameToString:1;
};

struct SRLScopeTagSet {
    void *_field1[4];
};

struct _LinphoneRingtonePlayer {
    id _field1;
    id _field2;
    CDUnknownFunctionPointerType _field3;
    void *_field4;
};

struct _SRLAPIRegistrationData {
    char *_field1;
    struct _SRLImplementationRegistrationData **_field2;
    union SRLAPIInstanceType _field3;
    unsigned short _field4;
    unsigned char _field5;
    unsigned char _field6;
    unsigned int :1;
    unsigned int :1;
};

struct _SRLImplementationRegistrationData {
    union SRLImplementationInstanceType _field1;
    union SRLImplementationInstanceType _field2;
    CDUnknownFunctionPointerType _field3;
    unsigned char _field4;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
};

struct _opaque_pthread_mutex_t {
    long long __sig;
    char __opaque[56];
};

struct objc_metadata_hider_ptr<const MLKITx__SRLBindingsRegistrationData> {
    struct MLKITx__SRLBindingsRegistrationData *_field1;
};

struct sockaddr {
    unsigned char _field1;
    unsigned char _field2;
    char _field3[14];
};

struct stat {
    int st_dev;
    unsigned short st_mode;
    unsigned short st_nlink;
    unsigned long long st_ino;
    unsigned int st_uid;
    unsigned int st_gid;
    int st_rdev;
    struct timespec st_atimespec;
    struct timespec st_mtimespec;
    struct timespec st_ctimespec;
    struct timespec st_birthtimespec;
    long long st_size;
    long long st_blocks;
    int st_blksize;
    unsigned int st_flags;
    unsigned int st_gen;
    int st_lspare;
    long long st_qspare[2];
};

struct timespec {
    long long tv_sec;
    long long tv_nsec;
};

struct unique_ptr<MLKITx_SRLMemoizingScopeIvars, std::__1::default_delete<MLKITx_SRLMemoizingScopeIvars>> {
    struct __compressed_pair<MLKITx_SRLMemoizingScopeIvars *, std::__1::default_delete<MLKITx_SRLMemoizingScopeIvars>> {
        struct MLKITx_SRLMemoizingScopeIvars *__value_;
    } __ptr_;
};

struct unique_ptr<MLKITx_SRLRegistryIvars, std::__1::default_delete<MLKITx_SRLRegistryIvars>> {
    struct __compressed_pair<MLKITx_SRLRegistryIvars *, std::__1::default_delete<MLKITx_SRLRegistryIvars>> {
        struct MLKITx_SRLRegistryIvars *__value_;
    } __ptr_;
};

struct vector<const ocr::photo::LineBox *, std::__1::allocator<const ocr::photo::LineBox *>> {
    struct LineBox **_field1;
    struct LineBox **_field2;
    struct __compressed_pair<const ocr::photo::LineBox **, std::__1::allocator<const ocr::photo::LineBox *>> {
        struct LineBox **_field1;
    } _field3;
};

struct vector<ocr::photo::LineBox, std::__1::allocator<ocr::photo::LineBox>> {
    struct LineBox *_field1;
    struct LineBox *_field2;
    struct __compressed_pair<ocr::photo::LineBox *, std::__1::allocator<ocr::photo::LineBox>> {
        struct LineBox *_field1;
    } _field3;
};

#pragma mark Typedef'd Structures

typedef struct {
    _Bool _field1;
    _Bool _field2;
    _Bool _field3;
    _Bool _field4;
    _Bool _field5;
    _Bool _field6;
    _Bool _field7;
} CDStruct_e38957e0;

typedef struct {
    _Bool _field1;
    unsigned char _field2;
    _Bool _field3;
    unsigned long long _field4;
} CDStruct_6a6a01a4;

typedef struct {
    unsigned int _field1;
    unsigned int _field2;
} CDStruct_c0454aff;

typedef struct {
    unsigned long long _field1;
    id *_field2;
    unsigned long long *_field3;
    unsigned long long _field4[5];
} CDStruct_70511ce9;

typedef struct {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
} CDStruct_a734b2e2;

typedef struct {
    long long value;
    int timescale;
    unsigned int flags;
    long long epoch;
} CDStruct_1b6d18a9;

typedef struct CDStruct_183601bc;

typedef struct {
    CDStruct_183601bc *impl;
    char *data;
    unsigned long long length;
    unsigned long long bitPos;
} CDStruct_6162cc1a;

typedef struct {
    CDStruct_183601bc *_field1;
    CDStruct_183601bc *_field2;
    CDStruct_183601bc *_field3;
    CDStruct_183601bc *_field4;
    struct LmiAllocatorS_ *_field5;
} CDStruct_632cb68a;

typedef struct {
    struct LmiAllocatorS_ *allocator;
    char *buf;
    unsigned long long size;
    unsigned long long capacity;
} CDStruct_890fc611;

typedef struct {
    struct LmiAllocatorS_ *alloc;
    long long trackPeriod;
    long long lastSampleTime;
    long long maxFirstHalfPeriod;
    long long maxSecondHalfPeriod;
    long long minFirstHalfPeriod;
    long long minSecondHalfPeriod;
    long long jitter;
    long long largeCounter;
    long long largeJitter;
} CDStruct_866181a7;

typedef struct {
    unsigned char _field1;
    CDStruct_183601bc *_field2;
    CDStruct_632cb68a _field3;
    int _field4;
    int _field5;
    int _field6;
    int _field7;
    struct _opaque_pthread_mutex_t _field8;
} CDStruct_4fd828e1;

typedef struct {
    struct LmiListNodeBase__LmiVoidPtr _field1;
    struct LmiAllocatorS_ *_field2;
} CDStruct_ecc2bd45;

typedef struct {
    struct _opaque_pthread_mutex_t mutex;
    struct LmiAllocatorS_ *alloc;
    unsigned long long totalBytes;
    unsigned long long lowestThresholdBytes;
    unsigned long long lowThresholdBytes;
    unsigned long long highThresholdBytes;
    unsigned long long highestThresholdBytes;
    unsigned long long maxThresholdBytes;
    unsigned char charging;
    unsigned char discharging;
    unsigned char allowSkew;
    unsigned int lastSampleNumReceived;
    long long lastPresentationTime;
    long long lastInputTime;
    long long lastOutputTime;
    CDStruct_890fc611 name;
    long long maxDelay;
    long long minDelayThreshold;
    long long maxDelayThreshold;
    long long flukeDelay;
    long long inputTrackerPeriod;
    long long minEnergy;
    long long minEnergyThreshold;
    long long energyTrackerPeriod;
    long long outputTrackerPeriod;
    unsigned long long consecutiveSpeechDetectedFrames;
    unsigned long long samplesAdded;
    unsigned long long samplesRemoved;
    CDStruct_6162cc1a buffer;
    unsigned int bufferSize;
    char *bufferReadPtr;
    char *bufferEndPtr;
    char *bufferWritePtr;
    unsigned int sampleRate;
    unsigned int bitsPerSample;
    unsigned int numberOfChannels;
    unsigned int samplesPerMs;
    unsigned int bytesPerMs;
    struct {
        int channelCount;
        int histStart;
        int histLength;
        int histOffset;
        unsigned int outputSampleCount;
        unsigned int coeffCacheHitCount;
        unsigned int coeffCacheMissCount;
        unsigned int addedSamples;
        unsigned int droppedSamples;
        int coeffCacheEntries;
        int coeffCacheLog2Entries;
        int coeffCacheEntryLength;
        int coeffCacheEntryLog2Length;
        long long coeffCacheHitFracDelayLimit;
        int coeffCacheIndexFracDelayShift;
        int coeffCacheSizeInBytes;
        long long coeffCacheFracDelay[2048];
        short *coeffCache;
        short historyBuffer[8192];
        int inputSampleRate;
        int outputSampleRate;
        long long lastInterpolationIndex;
        long long interpolationIndex;
        long long interpolationIndexInc;
        int sincTableIndexInc;
        short gainCorrection;
        short LowpassCutoff;
        short *SincTable;
        int SincTableZeroCrossings;
        int SincTableSize;
        int SincTableSizeMinusOne;
        int QualityLevel;
        struct LmiAllocatorS_ *allocator;
        unsigned char isFullyConstructed;
    } audioResampler;
    CDStruct_6162cc1a channelBuffer;
    CDStruct_6162cc1a resampleBuffer;
    struct LmiAudioBufferDebugInfo_ debugInfo;
    CDStruct_866181a7 energyTracker;
    CDStruct_866181a7 inputTracker;
    CDStruct_866181a7 outputTracker;
    void *userData;
    unsigned char emptyHangover;
    unsigned char read;
} CDStruct_83113961;

typedef struct {
    struct _opaque_pthread_mutex_t _field1;
    struct _opaque_pthread_mutex_t _field2;
    struct LmiAllocatorS_ *_field3;
    CDStruct_ecc2bd45 _field4;
    struct LmiVector_LmiVoidPtr _field5;
    struct LmiThread_ _field6;
    unsigned char _field7;
    unsigned int _field8;
    void *_field9;
} CDStruct_75ff4e6d;

// Template types
typedef struct objc_metadata_hider_ptr<const MLKITx__SRLBindingsRegistrationData> {
    struct MLKITx__SRLBindingsRegistrationData *_field1;
} objc_metadata_hider_ptr_b6fcfd97;

typedef struct vector<const ocr::photo::LineBox *, std::__1::allocator<const ocr::photo::LineBox *>> {
    struct LineBox **_field1;
    struct LineBox **_field2;
    struct __compressed_pair<const ocr::photo::LineBox **, std::__1::allocator<const ocr::photo::LineBox *>> {
        struct LineBox **_field1;
    } _field3;
} vector_74e00ca0;

typedef struct vector<ocr::photo::LineBox, std::__1::allocator<ocr::photo::LineBox>> {
    struct LineBox *_field1;
    struct LineBox *_field2;
    struct __compressed_pair<ocr::photo::LineBox *, std::__1::allocator<ocr::photo::LineBox>> {
        struct LineBox *_field1;
    } _field3;
} vector_0a9b862e;

#pragma mark Named Unions

union LmiListNodePtr__LmiVoidPtr {
    struct LmiListNode__LmiVoidPtr *_field1;
    struct LmiListNodeBase__LmiVoidPtr *_field2;
};

union SRLAPIInstanceType {
    struct {
        char *_field1;
        char *_field2;
    } _field1;
    CDUnknownFunctionPointerType _field2;
};

union SRLImplementationInstanceType {
    char *_field1;
    CDUnknownFunctionPointerType _field2;
};

#pragma mark Typedef'd Unions

typedef union {
    _Bool valueBool;
    int valueInt32;
    long long valueInt64;
    unsigned int valueUInt32;
    unsigned long long valueUInt64;
    float valueFloat;
    double valueDouble;
    NSData *valueData;
    NSString *valueString;
    GPBMessage *valueMessage;
    int valueEnum;
} CDUnion_88782d86;

