//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIApplicationDelegate.h"

@class CDVViewController, NSString, UIWindow;

@interface CDVAppDelegate : NSObject <UIApplicationDelegate>
{
    UIWindow *window;
    CDVViewController *viewController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CDVViewController *viewController; // @synthesize viewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

