//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CDVBackupInfo : NSObject
{
    NSString *original;
    NSString *backup;
    NSString *label;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *label; // @synthesize label;
@property(copy, nonatomic) NSString *backup; // @synthesize backup;
@property(copy, nonatomic) NSString *original; // @synthesize original;
- (_Bool)shouldRestore;
- (_Bool)shouldBackup;
- (_Bool)item:(id)arg1 isNewerThanItem:(id)arg2;
- (_Bool)file:(id)arg1 isNewerThanFile:(id)arg2;

@end

