//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CDVCommandDelegate.h"

@class CDVCommandQueue, CDVViewController, NSDictionary, NSRegularExpression, NSString;

@interface CDVCommandDelegateImpl : NSObject <CDVCommandDelegate>
{
    CDVViewController *_viewController;
    NSRegularExpression *_callbackIdPattern;
    CDVCommandQueue *_commandQueue;
    _Bool _delayResponses;
    CDUnknownBlockType urlTransformer;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType urlTransformer; // @synthesize urlTransformer;
@property(readonly, nonatomic) NSDictionary *settings;
- (id)userAgent;
- (void)runInBackground:(CDUnknownBlockType)arg1;
- (id)getCommandInstance:(id)arg1;
- (void)evalJs:(id)arg1 scheduledOnRunLoop:(_Bool)arg2;
- (void)evalJs:(id)arg1;
- (void)sendPluginResult:(id)arg1 callbackId:(id)arg2;
- (_Bool)isValidCallbackId:(id)arg1;
- (void)evalJsHelper:(id)arg1;
- (void)evalJsHelper2:(id)arg1;
- (void)flushCommandQueueWithDelayedJs;
- (id)pathForResource:(id)arg1;
- (id)initWithViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

