//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDVPluginResult, NSDictionary, NSString;

@protocol CDVCommandDelegate <NSObject>
@property(copy, nonatomic) CDUnknownBlockType urlTransformer;
@property(readonly, nonatomic) NSDictionary *settings;
- (NSString *)userAgent;
- (void)runInBackground:(void (^)(void))arg1;
- (void)evalJs:(NSString *)arg1 scheduledOnRunLoop:(_Bool)arg2;
- (void)evalJs:(NSString *)arg1;
- (void)sendPluginResult:(CDVPluginResult *)arg1 callbackId:(NSString *)arg2;
- (id)getCommandInstance:(NSString *)arg1;
- (NSString *)pathForResource:(NSString *)arg1;
@end

