//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDVViewController, NSMutableArray;

@interface CDVCommandQueue : NSObject
{
    long long _lastCommandQueueFlushRequestId;
    CDVViewController *_viewController;
    NSMutableArray *_queue;
    double _startExecutionTime;
}

- (void).cxx_destruct;
- (_Bool)execute:(id)arg1;
- (void)executePending;
- (void)fetchCommandsFromJs;
- (void)enqueueCommandBatch:(id)arg1;
- (void)resetRequestId;
- (void)dispose;
- (id)initWithViewController:(id)arg1;
@property(readonly, nonatomic) _Bool currentlyExecuting;

@end

