//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABPeoplePickerNavigationController.h"

@class NSDictionary, NSString;

@interface CDVContactsPicker : ABPeoplePickerNavigationController
{
    _Bool allowsEditing;
    NSString *callbackId;
    NSDictionary *options;
    NSDictionary *pickedContactDictionary;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *pickedContactDictionary; // @synthesize pickedContactDictionary;
@property(retain, nonatomic) NSDictionary *options; // @synthesize options;
@property(copy) NSString *callbackId; // @synthesize callbackId;
@property _Bool allowsEditing; // @synthesize allowsEditing;

@end

