//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface CDVDevice : CDVPlugin
{
}

+ (id)cordovaVersion;
- (_Bool)isVirtual;
- (id)deviceProperties;
- (void)getDeviceInfo:(id)arg1;
- (id)uniqueAppInstanceIdentifier:(id)arg1;

@end

