//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class NSURL;

@interface CDVHandleOpenURL : CDVPlugin
{
    _Bool _pageLoaded;
    NSURL *_url;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool pageLoaded; // @synthesize pageLoaded=_pageLoaded;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void)processOpenUrl:(id)arg1 pageLoaded:(_Bool)arg2;
- (void)applicationPageDidLoad:(id)arg1;
- (void)applicationLaunchedWithUrl:(id)arg1;
- (void)pluginInitialize;

@end

