//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

#import "NSXMLParserDelegate.h"

@class CDVWhitelist, NSMutableArray, NSString;

@interface CDVIntentAndNavigationFilter : CDVPlugin <NSXMLParserDelegate>
{
    NSMutableArray *_allowIntents;
    NSMutableArray *_allowNavigations;
    CDVWhitelist *_allowIntentsWhitelist;
    CDVWhitelist *_allowNavigationsWhitelist;
}

+ (_Bool)shouldOverrideLoadWithRequest:(id)arg1 navigationType:(int)arg2 filterValue:(long long)arg3;
+ (_Bool)shouldOpenURLRequest:(id)arg1 navigationType:(int)arg2;
+ (long long)filterUrl:(id)arg1 intentsWhitelist:(id)arg2 navigationsWhitelist:(id)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) CDVWhitelist *allowNavigationsWhitelist; // @synthesize allowNavigationsWhitelist=_allowNavigationsWhitelist;
@property(retain, nonatomic) CDVWhitelist *allowIntentsWhitelist; // @synthesize allowIntentsWhitelist=_allowIntentsWhitelist;
@property(retain, nonatomic) NSMutableArray *allowNavigations; // @synthesize allowNavigations=_allowNavigations;
@property(retain, nonatomic) NSMutableArray *allowIntents; // @synthesize allowIntents=_allowIntents;
- (_Bool)shouldOverrideLoadWithRequest:(id)arg1 navigationType:(int)arg2;
- (long long)filterUrl:(id)arg1;
- (void)pluginInitialize;
- (void)parser:(id)arg1 parseErrorOccurred:(id)arg2;
- (void)parserDidEndDocument:(id)arg1;
- (void)parserDidStartDocument:(id)arg1;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

