//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface CDVInAppBrowserNavigationController : UINavigationController
{
    id <CDVScreenOrientationDelegate> _orientationDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <CDVScreenOrientationDelegate> orientationDelegate; // @synthesize orientationDelegate=_orientationDelegate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (struct CGRect)invertFrameIfNeeded:(struct CGRect)arg1;
- (void)viewDidLoad;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;

@end

