//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface CDVInvokedUrlCommand : NSObject
{
    NSString *_callbackId;
    NSString *_className;
    NSString *_methodName;
    NSArray *_arguments;
}

+ (id)commandFromJson:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *methodName; // @synthesize methodName=_methodName;
@property(readonly, nonatomic) NSString *className; // @synthesize className=_className;
@property(readonly, nonatomic) NSString *callbackId; // @synthesize callbackId=_callbackId;
@property(readonly, nonatomic) NSArray *arguments; // @synthesize arguments=_arguments;
- (id)argumentAtIndex:(unsigned long long)arg1 withDefault:(id)arg2 andClass:(Class)arg3;
- (id)argumentAtIndex:(unsigned long long)arg1 withDefault:(id)arg2;
- (id)argumentAtIndex:(unsigned long long)arg1;
- (void)massageArguments;
- (id)initWithArguments:(id)arg1 callbackId:(id)arg2 className:(id)arg3 methodName:(id)arg4;
- (id)initFromJson:(id)arg1;

@end

