//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CDVInAppBrowserOptions : NSObject
{
    _Bool _location;
    _Bool _toolbar;
    _Bool _lefttoright;
    _Bool _toolbartranslucent;
    _Bool _hidenavigationbuttons;
    _Bool _cleardata;
    _Bool _clearcache;
    _Bool _clearsessioncache;
    _Bool _hidespinner;
    _Bool _enableviewportscale;
    _Bool _mediaplaybackrequiresuseraction;
    _Bool _allowinlinemediaplayback;
    _Bool _hidden;
    _Bool _disallowoverscroll;
    NSString *_closebuttoncaption;
    NSString *_closebuttoncolor;
    NSString *_toolbarposition;
    NSString *_toolbarcolor;
    NSString *_navigationbuttoncolor;
    NSString *_presentationstyle;
    NSString *_transitionstyle;
    NSString *_beforeload;
    NSString *_pagetitle;
    NSString *_backtitle;
}

+ (id)parseOptions:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *backtitle; // @synthesize backtitle=_backtitle;
@property(copy, nonatomic) NSString *pagetitle; // @synthesize pagetitle=_pagetitle;
@property(copy, nonatomic) NSString *beforeload; // @synthesize beforeload=_beforeload;
@property(nonatomic) _Bool disallowoverscroll; // @synthesize disallowoverscroll=_disallowoverscroll;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) _Bool allowinlinemediaplayback; // @synthesize allowinlinemediaplayback=_allowinlinemediaplayback;
@property(nonatomic) _Bool mediaplaybackrequiresuseraction; // @synthesize mediaplaybackrequiresuseraction=_mediaplaybackrequiresuseraction;
@property(nonatomic) _Bool enableviewportscale; // @synthesize enableviewportscale=_enableviewportscale;
@property(copy, nonatomic) NSString *transitionstyle; // @synthesize transitionstyle=_transitionstyle;
@property(copy, nonatomic) NSString *presentationstyle; // @synthesize presentationstyle=_presentationstyle;
@property(nonatomic) _Bool hidespinner; // @synthesize hidespinner=_hidespinner;
@property(nonatomic) _Bool clearsessioncache; // @synthesize clearsessioncache=_clearsessioncache;
@property(nonatomic) _Bool clearcache; // @synthesize clearcache=_clearcache;
@property(nonatomic) _Bool cleardata; // @synthesize cleardata=_cleardata;
@property(copy, nonatomic) NSString *navigationbuttoncolor; // @synthesize navigationbuttoncolor=_navigationbuttoncolor;
@property(nonatomic) _Bool hidenavigationbuttons; // @synthesize hidenavigationbuttons=_hidenavigationbuttons;
@property(nonatomic) _Bool toolbartranslucent; // @synthesize toolbartranslucent=_toolbartranslucent;
@property(copy, nonatomic) NSString *toolbarcolor; // @synthesize toolbarcolor=_toolbarcolor;
@property(copy, nonatomic) NSString *toolbarposition; // @synthesize toolbarposition=_toolbarposition;
@property(nonatomic) _Bool lefttoright; // @synthesize lefttoright=_lefttoright;
@property(copy, nonatomic) NSString *closebuttoncolor; // @synthesize closebuttoncolor=_closebuttoncolor;
@property(copy, nonatomic) NSString *closebuttoncaption; // @synthesize closebuttoncaption=_closebuttoncaption;
@property(nonatomic) _Bool toolbar; // @synthesize toolbar=_toolbar;
@property(nonatomic) _Bool location; // @synthesize location=_location;
- (id)init;

@end

