//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

#import "CBPeripheralManagerDelegate.h"
#import "CLLocationManagerDelegate.h"

@class CBPeripheralManager, CLLocationManager, CLRegion, LMLogger, NSDictionary, NSOperationQueue, NSString;

@interface CDVLocationManager : CDVPlugin <CLLocationManagerDelegate, CBPeripheralManagerDelegate>
{
    _Bool _debugLogEnabled;
    _Bool _debugNotificationsEnabled;
    _Bool _entered;
    NSOperationQueue *_queue;
    CLLocationManager *_locationManager;
    NSString *_delegateCallbackId;
    LMLogger *_logger;
    CBPeripheralManager *_peripheralManager;
    CLRegion *_advertisedBeaconRegion;
    NSDictionary *_advertisedPeripheralData;
}

- (void).cxx_destruct;
@property(retain) NSDictionary *advertisedPeripheralData; // @synthesize advertisedPeripheralData=_advertisedPeripheralData;
@property(retain) CLRegion *advertisedBeaconRegion; // @synthesize advertisedBeaconRegion=_advertisedBeaconRegion;
@property(retain) CBPeripheralManager *peripheralManager; // @synthesize peripheralManager=_peripheralManager;
@property _Bool entered; // @synthesize entered=_entered;
@property _Bool debugNotificationsEnabled; // @synthesize debugNotificationsEnabled=_debugNotificationsEnabled;
@property _Bool debugLogEnabled; // @synthesize debugLogEnabled=_debugLogEnabled;
@property(readonly, retain) LMLogger *logger; // @synthesize logger=_logger;
@property(retain) NSString *delegateCallbackId; // @synthesize delegateCallbackId=_delegateCallbackId;
@property(retain) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain) NSOperationQueue *queue; // @synthesize queue=_queue;
- (id)jsCallbackNameForSelector:(SEL)arg1;
- (id)getLogger;
- (id)mapOfBeacon:(id)arg1;
- (id)mapOfBeaconRegion:(id)arg1;
- (id)mapOfRegion:(id)arg1;
- (id)mapsOfRegions:(id)arg1;
- (id)peripherialStateAsString:(long long)arg1;
- (id)proximityAsString:(long long)arg1;
- (id)authorizationStatusAsString:(int)arg1;
- (id)regionStateAsString:(long long)arg1;
- (_Bool)isBelowIos7;
- (void)_handleExceptionOfCommand:(id)arg1:(id)arg2;
- (void)_handleCallSafely:(CDUnknownBlockType)arg1:(id)arg2:(_Bool)arg3;
- (void)_handleCallSafely:(CDUnknownBlockType)arg1:(id)arg2:(_Bool)arg3:(id)arg4;
- (void)_handleCallSafely:(CDUnknownBlockType)arg1:(id)arg2;
- (id)errorWithCode:(int)arg1 andDescription:(id)arg2;
- (id)parseErrorWithDescription:(id)arg1;
- (id)parseBeaconRegionFromMap:(id)arg1 andIdentifier:(id)arg2 returningError:(out id *)arg3;
- (id)parseCircularRegionFromMap:(id)arg1 andIdentifier:(id)arg2 returningError:(out id *)arg3;
- (id)parseRegion:(id)arg1 returningError:(out id *)arg2;
- (void)disableBluetooth:(id)arg1;
- (void)enableBluetooth:(id)arg1;
- (void)isBluetoothEnabled:(id)arg1;
- (void)isMonitoringAvailableForClass:(id)arg1;
- (void)stopAdvertising:(id)arg1;
- (void)startAdvertising:(id)arg1;
- (void)isAdvertising:(id)arg1;
- (void)isAdvertisingAvailable:(id)arg1;
- (void)peripheralManagerDidStartAdvertising:(id)arg1 error:(id)arg2;
- (void)peripheralManagerDidUpdateState:(id)arg1;
- (void)registerDelegateCallbackId:(id)arg1;
- (void)isRangingAvailable:(id)arg1;
- (void)getRangedRegions:(id)arg1;
- (void)getMonitoredRegions:(id)arg1;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)requestWhenInUseAuthorization:(id)arg1;
- (void)requestAlwaysAuthorization:(id)arg1;
- (void)getAuthorizationStatus:(id)arg1;
- (void)stopRangingBeaconsInRegion:(id)arg1;
- (void)startRangingBeaconsInRegion:(id)arg1;
- (void)requestStateForRegion:(id)arg1;
- (void)stopMonitoringForRegion:(id)arg1;
- (void)startMonitoringForRegion:(id)arg1;
- (void)appendToDeviceLog:(id)arg1;
- (void)enableDebugNotifications:(id)arg1;
- (void)disableDebugNotifications:(id)arg1;
- (void)enableDebugLogs:(id)arg1;
- (void)disableDebugLogs:(id)arg1;
- (void)onDomDelegateReady:(id)arg1;
- (void)locationManager:(id)arg1 didRangeBeacons:(id)arg2 inRegion:(id)arg3;
- (void)locationManager:(id)arg1 monitoringDidFailForRegion:(id)arg2 withError:(id)arg3;
- (void)locationManager:(id)arg1 didStartMonitoringForRegion:(id)arg2;
- (void)locationManager:(id)arg1 didExitRegion:(id)arg2;
- (void)locationManager:(id)arg1 didEnterRegion:(id)arg2;
- (void)locationManager:(id)arg1 didDetermineState:(long long)arg2 forRegion:(id)arg3;
- (void)checkIfDomSignaldDelegateReady;
- (void)checkEventQueue;
- (void)initEventQueue;
- (void)resumeEventPropagationToDom;
- (void)pauseEventPropagationToDom;
- (void)initPeripheralManager;
- (void)initLocationManager;
- (void)pluginInitialize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

