//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CDVFileSystem.h"

@class NSString;

@interface CDVLocalFilesystem : NSObject <CDVFileSystem>
{
    NSString *_name;
    NSString *_fsRoot;
    CDUnknownBlockType urlTransformer;
}

+ (id)getMimeTypeFromPath:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType urlTransformer; // @synthesize urlTransformer;
@property(retain, nonatomic) NSString *fsRoot; // @synthesize fsRoot=_fsRoot;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (id)mimeTypeForFileAtPath:(id)arg1;
- (void)getFileMetadataForURL:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)readFileAtURL:(id)arg1 start:(long long)arg2 end:(long long)arg3 callback:(CDUnknownBlockType)arg4;
- (void)copyFileToURL:(id)arg1 withName:(id)arg2 fromFileSystem:(id)arg3 atURL:(id)arg4 copy:(_Bool)arg5 callback:(CDUnknownBlockType)arg6;
- (_Bool)canCopyMoveSrc:(id)arg1 ToDestination:(id)arg2;
- (id)writeToFileAtURL:(id)arg1 withData:(id)arg2 append:(_Bool)arg3;
- (id)truncateFileAtURL:(id)arg1 atPosition:(unsigned long long)arg2;
- (unsigned long long)truncateFile:(id)arg1 atPosition:(unsigned long long)arg2;
- (id)readEntriesAtURL:(id)arg1;
- (id)fullPathForFileSystemPath:(id)arg1;
- (id)recursiveRemoveFileAtURL:(id)arg1;
- (id)removeFileAtURL:(id)arg1;
- (id)doRemove:(id)arg1;
- (id)setMetadataForURL:(id)arg1 withObject:(id)arg2;
- (id)getParentForURL:(id)arg1;
- (id)getFileForURL:(id)arg1 requestedPath:(id)arg2 options:(id)arg3;
- (_Bool)valueForKeyIsNumber:(id)arg1 key:(id)arg2;
- (id)normalizePath:(id)arg1;
- (id)URLforFilesystemPath:(id)arg1;
- (id)URLforFullPath:(id)arg1;
- (id)filesystemPathForURL:(id)arg1;
- (id)filesystemPathForFullPath:(id)arg1;
- (id)stripQueryParametersFromPath:(id)arg1;
- (id)makeEntryForPath:(id)arg1 isDirectory:(_Bool)arg2;
- (id)makeEntryForLocalURL:(id)arg1;
- (id)entryForLocalURI:(id)arg1;
- (id)initWithName:(id)arg1 root:(id)arg2;

@end

