//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLLocation, NSMutableArray, NSMutableDictionary;

@interface CDVLocationData : NSObject
{
    unsigned long long locationStatus;
    NSMutableArray *locationCallbacks;
    NSMutableDictionary *watchCallbacks;
    CLLocation *locationInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *watchCallbacks; // @synthesize watchCallbacks;
@property(retain, nonatomic) NSMutableArray *locationCallbacks; // @synthesize locationCallbacks;
@property(retain, nonatomic) CLLocation *locationInfo; // @synthesize locationInfo;
@property(nonatomic) unsigned long long locationStatus; // @synthesize locationStatus;
- (id)init;

@end

