//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABNewPersonViewController.h"

@class NSString;

@interface CDVNewContactsController : ABNewPersonViewController
{
    NSString *callbackId;
}

- (void).cxx_destruct;
@property(copy) NSString *callbackId; // @synthesize callbackId;

@end

