//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

#import "UIScrollViewDelegate.h"

@class NSString, UIColor, UIView;

@interface CDVStatusBar : CDVPlugin <UIScrollViewDelegate>
{
    _Bool _statusBarOverlaysWebView;
    UIView *_statusBarBackgroundView;
    _Bool _uiviewControllerBasedStatusBarAppearance;
    UIColor *_statusBarBackgroundColor;
    NSString *_eventsCallbackId;
    _Bool _statusBarVisible;
}

- (void).cxx_destruct;
@property _Bool statusBarVisible; // @synthesize statusBarVisible=_statusBarVisible;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)dealloc;
- (void)resizeWebView;
- (void)resizeStatusBarBackgroundView;
- (void)show:(id)arg1;
- (void)showStatusBar;
- (void)hide:(id)arg1;
- (void)hideStatusBar;
- (void)backgroundColorByHexString:(id)arg1;
- (void)_backgroundColorByHexString:(id)arg1;
- (void)backgroundColorByName:(id)arg1;
- (void)styleBlackOpaque:(id)arg1;
- (void)styleBlackTranslucent:(id)arg1;
- (void)styleLightContent:(id)arg1;
- (void)styleDefault:(id)arg1;
- (void)setStatusBarStyle:(id)arg1;
- (void)setStyleForStatusBar:(long long)arg1;
- (void)refreshStatusBarAppearance;
- (void)overlaysWebView:(id)arg1;
@property _Bool statusBarOverlaysWebView;
- (void)initializeStatusBarBackgroundView;
- (void)_ready:(id)arg1;
- (void)updateIsVisible:(_Bool)arg1;
- (void)fireTappedEvent;
- (void)onReset;
- (void)pluginInitialize;
- (void)statusBarDidChangeFrame:(id)arg1;
- (void)cordovaViewWillAppear:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)settingForKey:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

