//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

#import "CDVWebViewEngineProtocol.h"
#import "WKNavigationDelegate.h"
#import "WKScriptMessageHandler.h"

@class NSString, UIView;

@interface CDVWKWebViewEngine : CDVPlugin <CDVWebViewEngineProtocol, WKScriptMessageHandler, WKNavigationDelegate>
{
    UIView *_engineWebView;
    id <WKUIDelegate> _uiDelegate;
    id <WKScriptMessageHandler> _weakScriptMessageHandler;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <WKScriptMessageHandler> weakScriptMessageHandler; // @synthesize weakScriptMessageHandler=_weakScriptMessageHandler;
@property(retain, nonatomic) id <WKUIDelegate> uiDelegate; // @synthesize uiDelegate=_uiDelegate;
@property(retain, nonatomic) UIView *engineWebView; // @synthesize engineWebView=_engineWebView;
- (void)allowsBackForwardNavigationGestures:(id)arg1;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (_Bool)defaultResourcePolicyForURL:(id)arg1;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (id)webView;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (void)updateWithInfo:(id)arg1;
- (void)updateSettings:(id)arg1;
- (_Bool)canLoadRequest:(id)arg1;
- (id)URL;
- (id)loadHTMLString:(id)arg1 baseURL:(id)arg2;
- (id)loadRequest:(id)arg1;
- (_Bool)shouldReloadWebView:(id)arg1 title:(id)arg2;
- (_Bool)shouldReloadWebView;
- (void)onAppWillEnterForeground:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)addURLObserver;
- (void)onReset;
- (void)pluginInitialize;
- (id)createConfigurationFromSettings:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

