//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WKProcessPool;

@interface CDVWKProcessPoolFactory : NSObject
{
    WKProcessPool *_sharedPool;
}

+ (id)sharedFactory;
- (void).cxx_destruct;
@property(retain, nonatomic) WKProcessPool *sharedPool; // @synthesize sharedPool=_sharedPool;
- (id)sharedProcessPool;
- (id)init;

@end

