//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class CDVWKInAppBrowserViewController, NSRegularExpression, NSString, UIWindow;

@interface CDVWKInAppBrowser : CDVPlugin
{
    UIWindow *tmpWindow;
    NSString *_beforeload;
    _Bool _waitForBeforeload;
    long long _previousStatusBarStyle;
    CDVWKInAppBrowser *_instance;
    CDVWKInAppBrowserViewController *_inAppBrowserViewController;
    NSString *_callbackId;
    NSRegularExpression *_callbackIdPattern;
}

+ (id)getInstance;
- (void).cxx_destruct;
@property(copy, nonatomic) NSRegularExpression *callbackIdPattern; // @synthesize callbackIdPattern=_callbackIdPattern;
@property(copy, nonatomic) NSString *callbackId; // @synthesize callbackId=_callbackId;
@property(retain, nonatomic) CDVWKInAppBrowserViewController *inAppBrowserViewController; // @synthesize inAppBrowserViewController=_inAppBrowserViewController;
@property(retain, nonatomic) CDVWKInAppBrowser *instance; // @synthesize instance=_instance;
- (void)browserExit;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2;
- (void)didFinishNavigation:(id)arg1;
- (void)didStartProvisionalNavigation:(id)arg1;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (_Bool)isValidCallbackId:(id)arg1;
- (void)injectStyleFile:(id)arg1;
- (void)injectStyleCode:(id)arg1;
- (void)injectScriptFile:(id)arg1;
- (void)injectScriptCode:(id)arg1;
- (void)evaluateJavaScript:(id)arg1;
- (void)injectDeferredObject:(id)arg1 withWrapper:(id)arg2;
- (void)loadAfterBeforeload:(id)arg1;
- (void)openInSystem:(id)arg1;
- (void)openInCordovaWebView:(id)arg1 withOptions:(id)arg2;
- (void)hide:(id)arg1;
- (void)show:(id)arg1 withNoAnimate:(_Bool)arg2;
- (void)show:(id)arg1;
- (void)openInInAppBrowser:(id)arg1 withOptions:(id)arg2;
- (void)open:(id)arg1;
- (_Bool)isSystemUrl:(id)arg1;
- (void)close:(id)arg1;
- (void)onReset;
- (void)pluginInitialize;

@end

