//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, NSURL, NSURLRequest, UIView;

@protocol CDVWebViewEngineProtocol <NSObject>
@property(readonly, nonatomic) UIView *engineWebView;
- (void)updateWithInfo:(NSDictionary *)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)canLoadRequest:(NSURLRequest *)arg1;
- (NSURL *)URL;
- (void)evaluateJavaScript:(NSString *)arg1 completionHandler:(void (^)(id, NSError *))arg2;
- (id)loadHTMLString:(NSString *)arg1 baseURL:(NSURL *)arg2;
- (id)loadRequest:(NSURLRequest *)arg1;
@end

