//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface CTBCDeviceUtil : CDVPlugin
{
}

+ (_Bool)checkIfPromotionTriggered:(id)arg1 withTriggeredPromotions:(id)arg2;
+ (id)getValidPromotions:(id)arg1;
+ (void)processBeaconPromotion:(id)arg1;
- (void)writePromotionsToNativeStorage:(id)arg1;
- (void)getMessageNumberForClickedPromotion:(id)arg1;
- (void)getBeaconRegions:(id)arg1;
- (void)getNewlyTriggeredPromotions:(id)arg1;
- (void)markPromotionTriggered:(id)arg1;
- (void)copyTxt:(id)arg1;
- (void)hasSpeechPermission:(id)arg1;
- (void)startApp:(id)arg1;
- (void)setTextZoom:(id)arg1;
- (void)getStatusBarHeight:(id)arg1;
- (void)requestAlbumPermission:(id)arg1;
- (void)saveToPhotoAlbum:(id)arg1;

@end

