//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSUserDefaults;

@interface CTBCPromotionNativeStorageHandler : NSObject
{
    NSUserDefaults *_defaults;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)parseUUIDs:(id)arg1;
- (id)convertToJsonFromDict:(id)arg1;
- (id)convertToJsonFromArray:(id)arg1;
- (id)convertToArrayFromStr:(id)arg1;
- (id)convertToDictFromStr:(id)arg1;
- (int)getLocalNotificationIdSeq;
- (_Bool)writeLocalNotificationIdSeq:(int)arg1;
- (id)getPromotionsFromNativeStorage;
- (id)getPromotionsByUUID:(id)arg1;
- (id)getMessageNumber:(id)arg1;
- (id)getBeaconRegions;
- (id)getTriggeredPromotions:(_Bool)arg1;
- (_Bool)markPromotionTriggered:(id)arg1 andIsNewly:(_Bool)arg2;
- (_Bool)writePromotions:(id)arg1;
- (id)init;

@end

