//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface DeviceAuthPlugin : CDVPlugin
{
}

- (void)getDeviceDisplayName:(id)arg1;
- (void)setDeviceDisplayName:(id)arg1;
- (void)getDeviceUUID:(id)arg1;
- (void)getOsModel:(id)arg1;
- (void)init:(id)arg1;

@end

