//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

#import "CBCentralManagerDelegate.h"
#import "CLLocationManagerDelegate.h"

@class CBCentralManager, CLLocationManager, CMMotionActivityManager, CMPedometer, CNContactStore, EKEventStore, NSOperationQueue, NSString, NSUserDefaults;

@interface Diagnostic : CDVPlugin <CBCentralManagerDelegate, CLLocationManagerDelegate>
{
    CBCentralManager *_bluetoothManager;
    CLLocationManager *_locationManager;
    CMMotionActivityManager *_motionManager;
    NSOperationQueue *_motionActivityQueue;
    NSString *_locationRequestCallbackId;
    EKEventStore *_eventStore;
    NSString *_currentLocationAuthorizationStatus;
    CNContactStore *_contactStore;
    CMPedometer *_cmPedometer;
    NSUserDefaults *_settings;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSUserDefaults *settings; // @synthesize settings=_settings;
@property(retain, nonatomic) CMPedometer *cmPedometer; // @synthesize cmPedometer=_cmPedometer;
@property(retain, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(retain, nonatomic) NSString *currentLocationAuthorizationStatus; // @synthesize currentLocationAuthorizationStatus=_currentLocationAuthorizationStatus;
@property(retain, nonatomic) EKEventStore *eventStore; // @synthesize eventStore=_eventStore;
@property(retain, nonatomic) NSString *locationRequestCallbackId; // @synthesize locationRequestCallbackId=_locationRequestCallbackId;
@property(retain, nonatomic) NSOperationQueue *motionActivityQueue; // @synthesize motionActivityQueue=_motionActivityQueue;
@property(retain, nonatomic) CMMotionActivityManager *motionManager; // @synthesize motionManager=_motionManager;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) CBCentralManager *bluetoothManager; // @synthesize bluetoothManager=_bluetoothManager;
- (void)centralManagerDidUpdateState:(id)arg1;
- (id)getBluetoothState;
- (id)objectToJsonString:(id)arg1;
- (id)arrayToJsonString:(id)arg1;
- (_Bool)connectedToWifi;
- (id)getCameraRollAuthorizationStatusAsString:(long long)arg1;
- (id)getCameraRollAuthorizationStatus;
- (_Bool)isCameraAuthorized;
- (_Bool)isCameraPresent;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (_Bool)isLocationAuthorized;
- (id)getLocationAuthorizationStatusAsString:(int)arg1;
- (_Bool)isMotionRequestOutcomeAvailable;
- (_Bool)isMotionAvailable;
- (void)_isRegisteredForRemoteNotifications:(CDUnknownBlockType)arg1;
- (id)getSetting:(id)arg1;
- (void)setSetting:(id)arg1 forValue:(id)arg2;
- (void)jsCallback:(id)arg1;
- (void)handlePluginException:(id)arg1:(id)arg2;
- (void)sendPluginResultBool:(_Bool)arg1:(id)arg2;
- (void)sendPluginResult:(id)arg1:(id)arg2;
- (void)_requestMotionAuthorization:(id)arg1;
- (void)requestMotionAuthorization:(id)arg1;
- (void)getMotionAuthorizationStatus:(id)arg1;
- (void)isMotionRequestOutcomeAvailable:(id)arg1;
- (void)isMotionAvailable:(id)arg1;
- (void)getBackgroundRefreshStatus:(id)arg1;
- (void)requestRemindersAuthorization:(id)arg1;
- (void)isRemindersAuthorized:(id)arg1;
- (void)getRemindersAuthorizationStatus:(id)arg1;
- (void)requestCalendarAuthorization:(id)arg1;
- (void)isCalendarAuthorized:(id)arg1;
- (void)getCalendarAuthorizationStatus:(id)arg1;
- (void)requestAddressBookAuthorization:(id)arg1;
- (void)isAddressBookAuthorized:(id)arg1;
- (void)getAddressBookAuthorizationStatus:(id)arg1;
- (void)getRemoteNotificationsAuthorizationStatus:(id)arg1;
- (void)isRegisteredForRemoteNotifications:(id)arg1;
- (void)getRemoteNotificationTypesResult:(id)arg1:(_Bool)arg2:(_Bool)arg3:(_Bool)arg4:(_Bool)arg5;
- (void)getRemoteNotificationTypes:(id)arg1;
- (void)isRemoteNotificationsEnabledResult:(_Bool)arg1:(id)arg2;
- (void)isRemoteNotificationsEnabled:(id)arg1;
- (void)requestMicrophoneAuthorization:(id)arg1;
- (void)getMicrophoneAuthorizationStatus:(id)arg1;
- (void)isMicrophoneAuthorized:(id)arg1;
- (void)switchToLocationSettings:(id)arg1;
- (void)switchToSettings:(id)arg1;
- (void)requestBluetoothAuthorization:(id)arg1;
- (void)getBluetoothState:(id)arg1;
- (void)isBluetoothAvailable:(id)arg1;
- (_Bool)isWifiEnabled;
- (void)isWifiEnabled:(id)arg1;
- (void)isWifiAvailable:(id)arg1;
- (void)requestCameraRollAuthorization:(id)arg1;
- (void)getCameraRollAuthorizationStatus:(id)arg1;
- (void)isCameraRollAuthorized:(id)arg1;
- (void)requestCameraAuthorization:(id)arg1;
- (void)getCameraAuthorizationStatus:(id)arg1;
- (void)isCameraAuthorized:(id)arg1;
- (void)isCameraPresent:(id)arg1;
- (void)isCameraAvailable:(id)arg1;
- (void)requestLocationAuthorization:(id)arg1;
- (void)getLocationAuthorizationStatus:(id)arg1;
- (void)isLocationAuthorized:(id)arg1;
- (void)isLocationEnabled:(id)arg1;
- (void)isLocationAvailable:(id)arg1;
- (void)pluginInitialize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

