//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface FidoPlugin : CDVPlugin
{
}

- (void)getOldCustSeqFIDO:(id)arg1;
- (void)sendResultWithArgs:(id)arg1 andCallbackId:(id)arg2;
- (void)checkFeatureAvailFIDO:(id)arg1;
- (void)checkFingerAvailFIDO:(id)arg1;
- (void)setFeatureParamFIDO:(id)arg1;
- (void)checkFingerPrintHashFIDO:(id)arg1;
- (void)decryptDataFIDO:(id)arg1;
- (void)encryptDataFIDO:(id)arg1;
- (void)getTrxSignatureFIDO:(id)arg1;
- (void)getLoginSignatureFIDO:(id)arg1;
- (void)setFeatureFIDO:(id)arg1;
- (void)setCustSeqFIDO:(id)arg1;
- (void)genDeviceFIDO:(id)arg1;
- (void)getCustSeqFIDO:(id)arg1;
- (void)getDeviceDataFIDO:(id)arg1;
- (void)initialize:(id)arg1;

@end

