//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@protocol GIPClock <NSObject>
- (long long)uptimeMilliseconds;
- (long long)bootTimeMilliseconds;
- (long long)currentTimeMilliseconds;
- (void)scheduleAfterTimeInterval:(double)arg1 block:(void (^)(void))arg2;
- (NSDate *)now;
- (double)elapsedTimeSince:(NSDate *)arg1;
@end

