//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MLKITx_GIPLogMessage;

@protocol GIPLogger
- (id <GIPLogFilter>)filter;
- (void)logWithMessage:(MLKITx_GIPLogMessage *)arg1;
@end

