//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MLKITx_GIPLogMessage;

@protocol GIPLogMultiplexing
- (void)removeAsyncLogger:(id <GIPAsyncLogger>)arg1;
- (void)addAsyncLogger:(id <GIPAsyncLogger>)arg1;
- (void)removeSyncLogger:(id <GIPSyncLogger>)arg1;
- (void)addSyncLogger:(id <GIPSyncLogger>)arg1;
- (void)removeLogFilter:(id <GIPLogFilter>)arg1;
- (void)addLogFilter:(id <GIPLogFilter>)arg1;
- (void)logWithMessage:(MLKITx_GIPLogMessage *)arg1;
@end

