//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface GULCCComponentContainer : NSObject
{
    id _context;
    NSMutableDictionary *_components;
    NSMutableDictionary *_cachedInstances;
    NSMutableArray *_eagerProtocolsToInstantiate;
}

+ (void)registerAsComponentRegistrant:(Class)arg1 inSet:(id)arg2;
+ (void)registerAsComponentRegistrant:(Class)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *eagerProtocolsToInstantiate; // @synthesize eagerProtocolsToInstantiate=_eagerProtocolsToInstantiate;
@property(retain, nonatomic) NSMutableDictionary *cachedInstances; // @synthesize cachedInstances=_cachedInstances;
@property(retain, nonatomic) NSMutableDictionary *components; // @synthesize components=_components;
@property(readonly, nonatomic) __weak id context; // @synthesize context=_context;
- (void)removeAllCachedInstances;
- (id)instanceForProtocol:(id)arg1;
- (id)instantiateInstanceForProtocol:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)instantiateEagerComponents;
- (void)populateComponentsFromRegisteredClasses:(id)arg1 withContext:(id)arg2;
- (id)initWithContext:(id)arg1 registrants:(id)arg2;
- (id)initWithContext:(id)arg1;

@end

