//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileCoordinator, NSString, NSURL;

@interface GULHeartbeatDateStorage : NSObject
{
    NSURL *_fileURL;
    NSFileCoordinator *_fileCoordinator;
    NSString *_fileName;
}

+ (void)checkAndCreateDirectory:(id)arg1 fileCoordinator:(id)arg2;
+ (id)directoryPathURL;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(readonly, nonatomic) NSFileCoordinator *fileCoordinator; // @synthesize fileCoordinator=_fileCoordinator;
- (_Bool)writeDictionary:(id)arg1 forWritingURL:(id)arg2 error:(id *)arg3;
- (_Bool)setHearbeatDate:(id)arg1 forTag:(id)arg2;
- (id)heartbeatDateForTag:(id)arg1;
- (id)heartbeatDictionaryWithFileURL:(id)arg1;
@property(readonly, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
- (id)initWithFileName:(id)arg1;

@end

