//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WLSecurityUtils.h"

@interface HybridSecurityUtils : WLSecurityUtils
{
}

+ (_Bool)isPath:(id)arg1 ofExtensions:(id)arg2;
+ (id)getIgnoredFileExtensionsArray;
+ (_Bool)shouldIgnoreMediaFiles;
+ (void)setWebResourcesChecksum:(id)arg1;
+ (_Bool)shouldCalculateWebResourcesChecksum;
+ (void)updateLocalWebResourcesChecksumIfNeeded;
+ (void)resetWebResourcesCheckSum;
+ (_Bool)testWebResourcesChecksum;
+ (id)calculateWebResourcesChecksum;

@end

