//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class NSData;

@interface IBMSessionKeyGenerator : CDVPlugin
{
    NSData *_sessionKey;
    NSData *_sessionIV;
}

+ (id)bytesFromHexString:(id)arg1;
+ (void)set_secret_key:(id)arg1 keyData:(id)arg2 ivData:(id)arg3;
+ (void)initialize;
- (void).cxx_destruct;
@property(retain, nonatomic) NSData *sessionIV; // @synthesize sessionIV=_sessionIV;
@property(retain, nonatomic) NSData *sessionKey; // @synthesize sessionKey=_sessionKey;
- (void)decryptWithOldSecretKey:(id)arg1;
- (void)decryptWithSecretKey:(id)arg1;
- (void)encryptWithSecretKey:(id)arg1;
- (void)getLatestSecretKeyTimestamp:(id)arg1;
- (void)decrypt:(id)arg1;
- (void)encrypt:(id)arg1;
- (void)finishHandshake:(id)arg1;
- (id)decSecretData:(id)arg1 keyData:(id)arg2 ivData:(id)arg3 error:(id *)arg4;
- (id)encSecretData:(id)arg1 keyData:(id)arg2 ivData:(id)arg3 error:(id *)arg4;
- (id)decSessionData:(id)arg1 keyData:(id)arg2 ivData:(id)arg3 error:(id *)arg4;
- (id)encSessionData:(id)arg1 keyData:(id)arg2 ivData:(id)arg3 error:(id *)arg4;
- (id)convSessionIV:(id)arg1 error:(id *)arg2;
- (_Bool)verifySessionKeyHash:(id)arg1 ivCipherString:(id)arg2 sessionKeyHash:(id)arg3;
- (id)decSessionIV:(id)arg1 keyString:(id)arg2 error:(id *)arg3;
- (id)decSessionKey:(id)arg1 keyString:(id)arg2 error:(id *)arg3;
- (id)getRawStringFromData:(id)arg1;

@end

