//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface Line : CDVPlugin
{
}

+ (void)showShopDetail:(id)arg1;
+ (void)addFriend:(id)arg1;
+ (_Bool)shareImage:(id)arg1;
+ (_Bool)shareText:(id)arg1;
+ (_Bool)isLineInstalled;
+ (void)openLineInAppStore;
+ (id)pasteboard;
- (void)shareMsgToLine:(id)arg1;
- (void)shareImageToLine:(id)arg1;

@end

