//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LMLogger : NSObject
{
    _Bool _debugLogEnabled;
    _Bool _debugNotificationsEnabled;
}

@property _Bool debugNotificationsEnabled; // @synthesize debugNotificationsEnabled=_debugNotificationsEnabled;
@property _Bool debugLogEnabled; // @synthesize debugLogEnabled=_debugLogEnabled;
- (void)debugNotification:(id)arg1;
- (void)debugLog:(id)arg1;
- (void)postLocalNotificationWithMessage:(id)arg1;

@end

