//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface LoggerPlugin : CDVPlugin
{
}

- (void)processAutomaticTrigger:(id)arg1;
- (void)updateConfigFromServer:(id)arg1;
- (void)unsetUserContext:(id)arg1;
- (void)setUserContext:(id)arg1;
- (void)triggerFeedbackMode:(id)arg1;
- (void)sendAnalytics:(id)arg1;
- (void)send:(id)arg1;
- (void)getStatus:(id)arg1;
- (void)setNativeOptions:(id)arg1;
- (void)log:(id)arg1;
- (id)getCurrentConfiguration;

@end

