//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WLDelegate.h"

@class CDVInvokedUrlCommand, LoggerPlugin, NSString;

@interface LoggerSendDelegate : NSObject <WLDelegate>
{
    LoggerPlugin *plugin;
    CDVInvokedUrlCommand *command;
}

@property(retain) CDVInvokedUrlCommand *command; // @synthesize command;
@property(retain) LoggerPlugin *plugin; // @synthesize plugin;
- (void).cxx_destruct;
- (void)onFailure:(id)arg1;
- (void)onSuccess:(id)arg1;
- (id)initWithPlugin:(id)arg1 andCDVCommand:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

