//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GPBMessage, MLKITx_FBMLDurationStats, MLKITx_FBMLFirebaseMlSdkLogEvent, NSNumber;

@protocol MLKAnalyticsLoggerAggregationProvider <NSObject>
- (NSNumber *)durationMsFromLogEvent:(MLKITx_FBMLFirebaseMlSdkLogEvent *)arg1;
- (int)aggregationEventNameFromCommonLogEvent:(MLKITx_FBMLFirebaseMlSdkLogEvent *)arg1;
- (GPBMessage *)aggregatedLogEventKeyFromLogEvent:(MLKITx_FBMLFirebaseMlSdkLogEvent *)arg1;
- (MLKITx_FBMLFirebaseMlSdkLogEvent *)aggregatedLogEventFromLogEventKey:(GPBMessage *)arg1 count:(long long)arg2 durationStats:(MLKITx_FBMLDurationStats *)arg3;
@end

