//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GULCCComponentContainer, NSString;

@interface MLKContext : NSObject
{
    GULCCComponentContainer *_container;
}

+ (id)defaultContext;
@property(readonly, nonatomic) GULCCComponentContainer *container; // @synthesize container=_container;
- (void).cxx_destruct;
- (id)init;
- (void)delete;
@property(readonly, nonatomic) NSString *name;

@end

