//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MLKFileManager : NSObject
{
}

+ (long long)fileSizeAtURL:(id)arg1;
+ (id)freeSpaceSizeForDirectoryAtPath:(id)arg1 error:(id *)arg2;
+ (_Bool)addSkipBackupAttributeToDirectoryAtURL:(id)arg1 error:(id *)arg2;
+ (_Bool)moveItemFromURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
+ (_Bool)removeEmptyDirectoryAtURL:(id)arg1 error:(id *)arg2;
+ (_Bool)removeItemIfExistsAtURL:(id)arg1 error:(id *)arg2;
+ (_Bool)isFileReachableAtURL:(id)arg1;
+ (id)applicationSupportDirectoryURL;

@end

