//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MLKITx_GIPSafeParameter.h"

@class NSString;

@interface MLKITx_GIPSafeStringParameter : MLKITx_GIPSafeParameter
{
    NSString *_stringValue;
}

+ (id)parameterWithString:(id)arg1 type:(unsigned long long)arg2;
@property(readonly, nonatomic) NSString *stringValue; // @synthesize stringValue=_stringValue;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithString:(id)arg1 type:(unsigned long long)arg2;

@end

