//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_FBMLInferenceCommonLogEvent, MLKITx_FBMLTranslatorOptions;

@interface MLKITx_FBMLOnDeviceTranslationLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int downloadHTTPResponseCode; // @dynamic downloadHTTPResponseCode;
@property(nonatomic) _Bool hasDownloadHTTPResponseCode; // @dynamic hasDownloadHTTPResponseCode;
@property(nonatomic) _Bool hasInferenceCommonLogEvent; // @dynamic hasInferenceCommonLogEvent;
@property(nonatomic) _Bool hasInputLength; // @dynamic hasInputLength;
@property(nonatomic) _Bool hasLoadDictionaryErrorCode; // @dynamic hasLoadDictionaryErrorCode;
@property(nonatomic) _Bool hasOptions; // @dynamic hasOptions;
@property(nonatomic) _Bool hasOutputLength; // @dynamic hasOutputLength;
@property(nonatomic) _Bool hasStatus; // @dynamic hasStatus;
@property(nonatomic) _Bool hasTranslateResultStatusCode; // @dynamic hasTranslateResultStatusCode;
@property(retain, nonatomic) MLKITx_FBMLInferenceCommonLogEvent *inferenceCommonLogEvent; // @dynamic inferenceCommonLogEvent;
@property(nonatomic) int inputLength; // @dynamic inputLength;
@property(nonatomic) int loadDictionaryErrorCode; // @dynamic loadDictionaryErrorCode;
@property(retain, nonatomic) MLKITx_FBMLTranslatorOptions *options; // @dynamic options;
@property(nonatomic) int outputLength; // @dynamic outputLength;
@property(nonatomic) int status; // @dynamic status;
@property(nonatomic) int translateResultStatusCode; // @dynamic translateResultStatusCode;

@end

