//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_FBMLModelOptions;

@interface MLKITx_FBMLModelDownloadLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long downloadFailureStatus; // @dynamic downloadFailureStatus;
@property(nonatomic) int downloadStatus; // @dynamic downloadStatus;
@property(nonatomic) int errorCode; // @dynamic errorCode;
@property(nonatomic) unsigned long long exactDownloadDurationMs; // @dynamic exactDownloadDurationMs;
@property(nonatomic) _Bool hasDownloadFailureStatus; // @dynamic hasDownloadFailureStatus;
@property(nonatomic) _Bool hasDownloadStatus; // @dynamic hasDownloadStatus;
@property(nonatomic) _Bool hasErrorCode; // @dynamic hasErrorCode;
@property(nonatomic) _Bool hasExactDownloadDurationMs; // @dynamic hasExactDownloadDurationMs;
@property(nonatomic) _Bool hasOptions; // @dynamic hasOptions;
@property(nonatomic) _Bool hasRoughDownloadDurationMs; // @dynamic hasRoughDownloadDurationMs;
@property(retain, nonatomic) MLKITx_FBMLModelOptions *options; // @dynamic options;
@property(nonatomic) unsigned long long roughDownloadDurationMs; // @dynamic roughDownloadDurationMs;

@end

