//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MLKITx_GMVTextFeatureBox : NSObject
{
    double _angle;
    struct CGRect _bounds;
}

@property(readonly) double angle; // @synthesize angle=_angle;
@property(readonly) struct CGRect bounds; // @synthesize bounds=_bounds;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWith:(struct CGPoint)arg1 size:(struct CGSize)arg2 angle:(double)arg3;

@end

