//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface MLKITx_EXHScope : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *configPackage; // @dynamic configPackage;
@property(nonatomic) _Bool hasConfigPackage; // @dynamic hasConfigPackage;
@property(nonatomic) _Bool hasVersionCode; // @dynamic hasVersionCode;
@property(nonatomic) long long versionCode; // @dynamic versionCode;

@end

