//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class MLKITx_SRLImplementationConfiguration, NSSet;

@interface MLKITx_SRLImplementation : NSObject <NSCopying>
{
    unsigned char _scopeType;
    _Bool _isComponentBinding;
    _Bool _ignoreAccountIDInInit;
    id <SRLInstanceType> _instanceType;
    unsigned long long _lifetime;
    CDUnknownBlockType _factoryBlock;
    NSSet *_apiDependencies;
    MLKITx_SRLImplementationConfiguration *_configuration;
}

@property(readonly, nonatomic) _Bool ignoreAccountIDInInit; // @synthesize ignoreAccountIDInInit=_ignoreAccountIDInInit;
@property(readonly, nonatomic) MLKITx_SRLImplementationConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) NSSet *apiDependencies; // @synthesize apiDependencies=_apiDependencies;
@property(readonly, nonatomic) _Bool isComponentBinding; // @synthesize isComponentBinding=_isComponentBinding;
@property(readonly, nonatomic) CDUnknownBlockType factoryBlock; // @synthesize factoryBlock=_factoryBlock;
@property(readonly, nonatomic) unsigned char scopeType; // @synthesize scopeType=_scopeType;
@property(readonly, nonatomic) unsigned long long lifetime; // @synthesize lifetime=_lifetime;
@property(readonly, nonatomic) id <SRLInstanceType> instanceType; // @synthesize instanceType=_instanceType;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)initWithInstanceType:(id)arg1 lifetime:(unsigned long long)arg2 scope:(unsigned char)arg3 factoryBlock:(CDUnknownBlockType)arg4 apiDependencies:(id)arg5 configuration:(id)arg6 isComponentBinding:(_Bool)arg7;

@end

