//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_LogResponseDetails : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLogRequestIndex; // @dynamic hasLogRequestIndex;
@property(nonatomic) _Bool hasResponseAction; // @dynamic hasResponseAction;
@property(nonatomic) int logRequestIndex; // @dynamic logRequestIndex;
@property(nonatomic) int responseAction; // @dynamic responseAction;

@end

