//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_GMVPipelineAnalysis : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long analysisMs; // @dynamic analysisMs;
@property(nonatomic) _Bool hasAnalysisMs; // @dynamic hasAnalysisMs;
@property(nonatomic) _Bool hasNumResults; // @dynamic hasNumResults;
@property(nonatomic) long long numResults; // @dynamic numResults;

@end

