//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_FBMLFaceDetectorOptions, MLKITx_FBMLImageInfo, MLKITx_FBMLInferenceCommonLogEvent, MLKITx_GMVFaceInitializationOptions;

@interface MLKITx_FBMLOnDeviceFaceDetectionLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) unsigned int contourDetectedFaces; // @dynamic contourDetectedFaces;
@property(retain, nonatomic) MLKITx_FBMLFaceDetectorOptions *detectorOptions; // @dynamic detectorOptions;
@property(nonatomic) _Bool hasContourDetectedFaces; // @dynamic hasContourDetectedFaces;
@property(nonatomic) _Bool hasDetectorOptions; // @dynamic hasDetectorOptions;
@property(nonatomic) _Bool hasImageInfo; // @dynamic hasImageInfo;
@property(nonatomic) _Bool hasInferenceCommonLogEvent; // @dynamic hasInferenceCommonLogEvent;
@property(nonatomic) _Bool hasNonContourDetectedFaces; // @dynamic hasNonContourDetectedFaces;
@property(nonatomic) _Bool hasOptions; // @dynamic hasOptions;
@property(retain, nonatomic) MLKITx_FBMLImageInfo *imageInfo; // @dynamic imageInfo;
@property(retain, nonatomic) MLKITx_FBMLInferenceCommonLogEvent *inferenceCommonLogEvent; // @dynamic inferenceCommonLogEvent;
@property(nonatomic) unsigned int nonContourDetectedFaces; // @dynamic nonContourDetectedFaces;
@property(retain, nonatomic) MLKITx_GMVFaceInitializationOptions *options; // @dynamic options;

@end

