//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSHashTable, NSString;

@interface MLKITx_GIPPseudonymousIDStore : NSObject
{
    NSHashTable *_observers;
    _Bool _hasInitializedStorage;
}

+ (id)sharedInstance;
+ (void)disableForTest;
+ (void)enable;
+ (void)setDefaultDirectory:(id)arg1;
- (void).cxx_destruct;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)setPseudonymousIDFromResponse:(id)arg1;
- (void)updateRequestWithPseudonymousID:(id)arg1;
- (_Bool)isValidPseudonymousID:(id)arg1;
- (void)setPseudonymousIDWithoutCheckingEnabledStatus:(id)arg1;
@property(retain, nonatomic) NSString *pseudonymousID;
- (id)pseudonymousIDWithoutCheckingEnabledStatus;
- (id)pseudonymousIDURL;
- (_Bool)initializeStorage;
- (id)init;

@end

