//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCTClearcutLogTransformer.h"

@class MLKITx_CCTClearcutFlags, NSString;

@interface MLKITx_CCTLogSampler : NSObject <CCTClearcutLogTransformer>
{
    MLKITx_CCTClearcutFlags *_flags;
    NSString *_idfv;
}

@property(retain) NSString *idfv; // @synthesize idfv=_idfv;
@property(readonly, nonatomic) MLKITx_CCTClearcutFlags *flags; // @synthesize flags=_flags;
- (void).cxx_destruct;
- (_Bool)shouldSampleLocally:(id)arg1;
- (id)transform:(id)arg1;
- (id)initWithFlags:(id)arg1 idfv:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

