//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_GMVApplicationInfo, MLKITx_GMVBarcodeInitializationOptions, MLKITx_GMVFaceInitializationOptions, NSString;

@interface MLKITx_GMVInitializationEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) MLKITx_GMVApplicationInfo *appInfo; // @dynamic appInfo;
@property(retain, nonatomic) MLKITx_GMVBarcodeInitializationOptions *barcodeOptions; // @dynamic barcodeOptions;
@property(copy, nonatomic) NSString *errorMsg; // @dynamic errorMsg;
@property(retain, nonatomic) MLKITx_GMVFaceInitializationOptions *faceOptions; // @dynamic faceOptions;
@property(nonatomic) _Bool hasAppInfo; // @dynamic hasAppInfo;
@property(nonatomic) _Bool hasBarcodeOptions; // @dynamic hasBarcodeOptions;
@property(nonatomic) _Bool hasErrorMsg; // @dynamic hasErrorMsg;
@property(nonatomic) _Bool hasFaceOptions; // @dynamic hasFaceOptions;
@property(nonatomic) _Bool hasInitMs; // @dynamic hasInitMs;
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(nonatomic) long long initMs; // @dynamic initMs;
@property(copy, nonatomic) NSString *name; // @dynamic name;

@end

