//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface MLKITx_FBMLSystemInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *apiKey; // @dynamic apiKey;
@property(copy, nonatomic) NSString *appId; // @dynamic appId;
@property(copy, nonatomic) NSString *appVersion; // @dynamic appVersion;
@property(copy, nonatomic) NSString *firebaseProjectId; // @dynamic firebaseProjectId;
@property(copy, nonatomic) NSString *gcmSenderId; // @dynamic gcmSenderId;
@property(nonatomic) _Bool hasApiKey; // @dynamic hasApiKey;
@property(nonatomic) _Bool hasAppId; // @dynamic hasAppId;
@property(nonatomic) _Bool hasAppVersion; // @dynamic hasAppVersion;
@property(nonatomic) _Bool hasFirebaseProjectId; // @dynamic hasFirebaseProjectId;
@property(nonatomic) _Bool hasGcmSenderId; // @dynamic hasGcmSenderId;
@property(nonatomic) _Bool hasIsClearcutClient; // @dynamic hasIsClearcutClient;
@property(nonatomic) _Bool hasIsStandaloneMlkit; // @dynamic hasIsStandaloneMlkit;
@property(nonatomic) _Bool hasMlSdkInstanceId; // @dynamic hasMlSdkInstanceId;
@property(nonatomic) _Bool hasMlSdkVersion; // @dynamic hasMlSdkVersion;
@property(nonatomic) _Bool hasTfliteSchemaVersion; // @dynamic hasTfliteSchemaVersion;
@property(nonatomic) _Bool isClearcutClient; // @dynamic isClearcutClient;
@property(nonatomic) _Bool isStandaloneMlkit; // @dynamic isStandaloneMlkit;
@property(retain, nonatomic) NSMutableArray *languagesArray; // @dynamic languagesArray;
@property(readonly, nonatomic) unsigned long long languagesArray_Count; // @dynamic languagesArray_Count;
@property(copy, nonatomic) NSString *mlSdkInstanceId; // @dynamic mlSdkInstanceId;
@property(copy, nonatomic) NSString *mlSdkVersion; // @dynamic mlSdkVersion;
@property(copy, nonatomic) NSString *tfliteSchemaVersion; // @dynamic tfliteSchemaVersion;

@end

