//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface MLKITx_FBMLOnDeviceLanguageIdentificationLogEvent_IdentifyPossibleLanguagesResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *identifiedLanguagesArray; // @dynamic identifiedLanguagesArray;
@property(readonly, nonatomic) unsigned long long identifiedLanguagesArray_Count; // @dynamic identifiedLanguagesArray_Count;

@end

