//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_FBMLImageInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) unsigned int compressedImageSize; // @dynamic compressedImageSize;
@property(nonatomic) _Bool hasCompressedImageSize; // @dynamic hasCompressedImageSize;
@property(nonatomic) _Bool hasImageFormat; // @dynamic hasImageFormat;
@property(nonatomic) _Bool hasOriginalImageSize; // @dynamic hasOriginalImageSize;
@property(nonatomic) int imageFormat; // @dynamic imageFormat;
@property(nonatomic) unsigned int originalImageSize; // @dynamic originalImageSize;

@end

