//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GIPPseudonymousIDObserver.h"
#import "PHTPhenotypeInternal.h"

@class MLKITx_GIPPseudonymousIDStore, MLKITx_PHTCachedModTimeData, MLKITx_PHTPhenotypeLogger, NSFileManager, NSHashTable, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface MLKITx_PHTFlatFilePhenotype : NSObject <GIPPseudonymousIDObserver, PHTPhenotypeInternal>
{
    NSObject<OS_dispatch_queue> *_workQueue;
    NSObject<OS_dispatch_queue> *_completionQueue;
    NSMutableArray *_pendingSyncTasks;
    NSHashTable *_commitObservers;
    NSMutableDictionary *_tokenCache;
    long long _cacheTime;
    NSFileManager *_fileManager;
    id <CCTClockProtocol> _clock;
    MLKITx_GIPPseudonymousIDStore *_pseudonymousIDStore;
    MLKITx_PHTPhenotypeLogger *_logger;
    MLKITx_PHTCachedModTimeData *_cachedModTimeData;
    _Bool _debugForceSyncs;
    NSString *_overrideServerURL;
}

+ (id)phenotypeLogEvent;
+ (id)phenotypeApiErrorInfo:(id)arg1;
+ (id)phenotypeLogEventWithApplicationInfo:(id)arg1 error:(id)arg2;
+ (id)applicationInfoWithPackageName:(id)arg1 user:(id)arg2 logSources:(id)arg3 duration:(long long)arg4;
+ (void)useLocalCachesDirectory;
+ (void)setDefaultDirectory:(id)arg1;
+ (id)sharedInstance;
@property(copy, nonatomic) NSString *overrideServerURL; // @synthesize overrideServerURL=_overrideServerURL;
@property(nonatomic) _Bool debugForceSyncs; // @synthesize debugForceSyncs=_debugForceSyncs;
- (void).cxx_destruct;
- (void)invalidateTokenCache;
- (void)setCachedTokens:(id)arg1 cacheKey:(id)arg2 modificationTimeMilliseconds:(long long)arg3;
- (id)cachedTokensForKey:(id)arg1 modificationTimeMilliseconds:(long long)arg2;
- (long long)crossDirectoryModificationTimeMilliseconds;
- (void)pseudonymousIDDidReset:(id)arg1;
- (void)commitPhenotypeConfiguration:(CDUnknownBlockType)arg1;
- (void)resetRegisterPhenotypeToken;
- (void)registerPhenotype:(CDUnknownBlockType)arg1;
- (_Bool)removeCommittedCrossTokensForPackage:(id)arg1 error:(id *)arg2;
- (_Bool)removeCommittedSnapshotsForPackage:(id)arg1 error:(id *)arg2;
- (_Bool)removeUncommittedSnapshotsForPackage:(id)arg1 error:(id *)arg2;
- (void)addCrossTokens:(id)arg1 fromURL:(id)arg2;
- (id)readLogSourceMappingWithError:(id *)arg1;
- (void)notifyCommitObserversForPackage:(id)arg1 config:(id)arg2;
- (void)removeCommitObserver:(id)arg1;
- (void)addCommitObserver:(id)arg1;
- (void)logOperationWithPackageName:(id)arg1 user:(id)arg2 logSources:(id)arg3 error:(id)arg4 duration:(long long)arg5 eventCode:(id)arg6;
- (void)setExternalExperimentIDs:(id)arg1 moduleNamespace:(id)arg2 logSource:(long long)arg3 callback:(CDUnknownBlockType)arg4;
- (void)committedConfigurationForPackage:(id)arg1 obfuscatedGaiaID:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)committedConfiguration:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)committedConfiguration:(id)arg1 user:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)experimentTokensForCurrentBundleWithCallback:(CDUnknownBlockType)arg1;
- (void)experimentTokens:(long long)arg1 user:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)peekConfiguration:(id)arg1 user:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)commitConfiguration:(id)arg1 user:(id)arg2 committer:(CDUnknownBlockType)arg3;
- (_Bool)packageRegistered:(id)arg1 error:(id *)arg2;
- (void)unregisterPackage:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)registerPackage:(id)arg1 logSources:(id)arg2 params:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)registerPackage:(id)arg1 version:(long long)arg2 logSources:(id)arg3 params:(id)arg4 callback:(CDUnknownBlockType)arg5;
- (void)syncNextSyncTask;
- (void)syncExperimentsWithServerInternal:(id)arg1 syncAfterConfiguration:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)syncExperimentsWithServer:(id)arg1 syncAfterConfiguration:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)syncExperimentsWithServer:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (id)init;
- (id)initWithClock:(id)arg1 pseudonymousIDStore:(id)arg2 logger:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

