//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_GMVFaceInitializationOptions : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int classification; // @dynamic classification;
@property(nonatomic) _Bool hasClassification; // @dynamic hasClassification;
@property(nonatomic) _Bool hasLandmark; // @dynamic hasLandmark;
@property(nonatomic) _Bool hasMinFaceSize; // @dynamic hasMinFaceSize;
@property(nonatomic) _Bool hasMode; // @dynamic hasMode;
@property(nonatomic) _Bool hasProminentFaceOnly; // @dynamic hasProminentFaceOnly;
@property(nonatomic) _Bool hasTracking; // @dynamic hasTracking;
@property(nonatomic) int landmark; // @dynamic landmark;
@property(nonatomic) float minFaceSize; // @dynamic minFaceSize;
@property(nonatomic) int mode; // @dynamic mode;
@property(nonatomic) _Bool prominentFaceOnly; // @dynamic prominentFaceOnly;
@property(nonatomic) _Bool tracking; // @dynamic tracking;

@end

