//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_FBMLInferenceCommonLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool autoManageModelOnBackground; // @dynamic autoManageModelOnBackground;
@property(nonatomic) _Bool autoManageModelOnLowMemory; // @dynamic autoManageModelOnLowMemory;
@property(nonatomic) unsigned long long durationMs; // @dynamic durationMs;
@property(nonatomic) int errorCode; // @dynamic errorCode;
@property(nonatomic) unsigned int eventsCount; // @dynamic eventsCount;
@property(nonatomic) _Bool hasAutoManageModelOnBackground; // @dynamic hasAutoManageModelOnBackground;
@property(nonatomic) _Bool hasAutoManageModelOnLowMemory; // @dynamic hasAutoManageModelOnLowMemory;
@property(nonatomic) _Bool hasDurationMs; // @dynamic hasDurationMs;
@property(nonatomic) _Bool hasErrorCode; // @dynamic hasErrorCode;
@property(nonatomic) _Bool hasEventsCount; // @dynamic hasEventsCount;
@property(nonatomic) _Bool hasIsColdCall; // @dynamic hasIsColdCall;
@property(nonatomic) _Bool hasIsNnApiEnabled; // @dynamic hasIsNnApiEnabled;
@property(nonatomic) _Bool isColdCall; // @dynamic isColdCall;
@property(nonatomic) _Bool isNnApiEnabled; // @dynamic isNnApiEnabled;

@end

