//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBEnumArray, MLKITx_FBMLImageInfo, MLKITx_FBMLInferenceCommonLogEvent, MLKITx_GMVBarcodeInitializationOptions;

@interface MLKITx_FBMLOnDeviceBarcodeDetectionLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPBEnumArray *detectedBarcodeFormatsArray; // @dynamic detectedBarcodeFormatsArray;
@property(readonly, nonatomic) unsigned long long detectedBarcodeFormatsArray_Count; // @dynamic detectedBarcodeFormatsArray_Count;
@property(retain, nonatomic) GPBEnumArray *detectedBarcodeValueTypesArray; // @dynamic detectedBarcodeValueTypesArray;
@property(readonly, nonatomic) unsigned long long detectedBarcodeValueTypesArray_Count; // @dynamic detectedBarcodeValueTypesArray_Count;
@property(nonatomic) _Bool hasImageInfo; // @dynamic hasImageInfo;
@property(nonatomic) _Bool hasInferenceCommonLogEvent; // @dynamic hasInferenceCommonLogEvent;
@property(nonatomic) _Bool hasOptions; // @dynamic hasOptions;
@property(retain, nonatomic) MLKITx_FBMLImageInfo *imageInfo; // @dynamic imageInfo;
@property(retain, nonatomic) MLKITx_FBMLInferenceCommonLogEvent *inferenceCommonLogEvent; // @dynamic inferenceCommonLogEvent;
@property(retain, nonatomic) MLKITx_GMVBarcodeInitializationOptions *options; // @dynamic options;

@end

