//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData;

@interface MLKITx_EPICrossExperimentToken : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSData *experimentToken; // @dynamic experimentToken;
@property(nonatomic) _Bool hasExperimentToken; // @dynamic hasExperimentToken;
@property(nonatomic) _Bool hasProvenance; // @dynamic hasProvenance;
@property(nonatomic) int provenance; // @dynamic provenance;

@end

