//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_EPIConfigurationSnapshot, MLKITx_EPIRegistrationData, MLKITx_EXHScope;

@interface MLKITx_EPIPackageData : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasRegistration; // @dynamic hasRegistration;
@property(nonatomic) _Bool hasScope; // @dynamic hasScope;
@property(nonatomic) _Bool hasSnapshot; // @dynamic hasSnapshot;
@property(retain, nonatomic) MLKITx_EPIRegistrationData *registration; // @dynamic registration;
@property(retain, nonatomic) MLKITx_EXHScope *scope; // @dynamic scope;
@property(retain, nonatomic) MLKITx_EPIConfigurationSnapshot *snapshot; // @dynamic snapshot;

@end

