//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBEnumArray, MLKITx_FBMLModelOptions;

@interface MLKITx_FBMLAutoMLImageLabelingLoadLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPBEnumArray *errorCodesArray; // @dynamic errorCodesArray;
@property(readonly, nonatomic) unsigned long long errorCodesArray_Count; // @dynamic errorCodesArray_Count;
@property(nonatomic) _Bool hasLocalModelOptions; // @dynamic hasLocalModelOptions;
@property(nonatomic) _Bool hasModelInitializationMs; // @dynamic hasModelInitializationMs;
@property(nonatomic) _Bool hasRemoteModelOptions; // @dynamic hasRemoteModelOptions;
@property(retain, nonatomic) MLKITx_FBMLModelOptions *localModelOptions; // @dynamic localModelOptions;
@property(nonatomic) unsigned long long modelInitializationMs; // @dynamic modelInitializationMs;
@property(retain, nonatomic) MLKITx_FBMLModelOptions *remoteModelOptions; // @dynamic remoteModelOptions;

@end

