//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class MLKITx_SRLMapBindingKey, NSString;

@interface MLKITx_SRLAPIKey : NSObject <NSCopying, NSSecureCoding>
{
    NSString *_identifier;
    MLKITx_SRLMapBindingKey *_mapBindingKey;
    id <SRLInstanceType> _instanceType;
}

+ (_Bool)supportsSecureCoding;
+ (id)apiKeyWithIdentifier:(id)arg1 instanceType:(id)arg2 mapBindingKey:(id)arg3;
@property(readonly, nonatomic) id <SRLInstanceType> instanceType; // @synthesize instanceType=_instanceType;
@property(readonly, nonatomic) MLKITx_SRLMapBindingKey *mapBindingKey; // @synthesize mapBindingKey=_mapBindingKey;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (_Bool)edo_isEDOValueType;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
@property(readonly, nonatomic) NSString *serviceName;
- (id)initWithIdentifier:(id)arg1 instanceType:(id)arg2 mapBindingKey:(id)arg3;

@end

