//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBEnumArray, MLKITx_FBMLOnDeviceImageLabelOptions;

@interface MLKITx_FBMLOnDeviceImageLabelLoadLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) MLKITx_FBMLOnDeviceImageLabelOptions *detectorOptions; // @dynamic detectorOptions;
@property(retain, nonatomic) GPBEnumArray *errorCodesArray; // @dynamic errorCodesArray;
@property(readonly, nonatomic) unsigned long long errorCodesArray_Count; // @dynamic errorCodesArray_Count;
@property(nonatomic) _Bool hasDetectorOptions; // @dynamic hasDetectorOptions;
@property(nonatomic) _Bool hasLoggingInitializationMs; // @dynamic hasLoggingInitializationMs;
@property(nonatomic) _Bool hasTotalInitializationMs; // @dynamic hasTotalInitializationMs;
@property(nonatomic) unsigned long long loggingInitializationMs; // @dynamic loggingInitializationMs;
@property(nonatomic) unsigned long long totalInitializationMs; // @dynamic totalInitializationMs;

@end

