//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_QosTiersOverride, NSMutableArray;

@interface MLKITx_LogResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasNextRequestWaitMillis; // @dynamic hasNextRequestWaitMillis;
@property(nonatomic) _Bool hasQosTier; // @dynamic hasQosTier;
@property(retain, nonatomic) NSMutableArray *logResponseDetailsArray; // @dynamic logResponseDetailsArray;
@property(readonly, nonatomic) unsigned long long logResponseDetailsArray_Count; // @dynamic logResponseDetailsArray_Count;
@property(nonatomic) long long nextRequestWaitMillis; // @dynamic nextRequestWaitMillis;
@property(retain, nonatomic) MLKITx_QosTiersOverride *qosTier; // @dynamic qosTier;

@end

