//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_GMVImageData, MLKITx_GMVPipelineAnalysis, NSMutableArray;

@interface MLKITx_GMVImageAnalysisEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *engineAnalysisArray; // @dynamic engineAnalysisArray;
@property(readonly, nonatomic) unsigned long long engineAnalysisArray_Count; // @dynamic engineAnalysisArray_Count;
@property(nonatomic) _Bool hasImageData; // @dynamic hasImageData;
@property(nonatomic) _Bool hasPipelineAnalysis; // @dynamic hasPipelineAnalysis;
@property(retain, nonatomic) MLKITx_GMVImageData *imageData; // @dynamic imageData;
@property(retain, nonatomic) MLKITx_GMVPipelineAnalysis *pipelineAnalysis; // @dynamic pipelineAnalysis;

@end

