//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class MLKITx_GIPLogCallstack, MLKITx_GIPLogMetadata, NSDictionary, NSString;

@interface MLKITx_GIPLogMessage : NSObject <NSCopying>
{
    unsigned long long _level;
    NSString *_format;
    NSString *_formattedString;
    NSString *_file;
    NSString *_function;
    unsigned long long _line;
    NSString *_threadName;
    NSString *_dispatchQueueLabel;
    MLKITx_GIPLogCallstack *_callstack;
    NSDictionary *_safeParameters;
    MLKITx_GIPLogMetadata *_logMetadata;
}

@property(readonly, nonatomic) MLKITx_GIPLogMetadata *logMetadata; // @synthesize logMetadata=_logMetadata;
@property(readonly, nonatomic) NSDictionary *safeParameters; // @synthesize safeParameters=_safeParameters;
@property(readonly, nonatomic) MLKITx_GIPLogCallstack *callstack; // @synthesize callstack=_callstack;
@property(readonly, nonatomic) NSString *dispatchQueueLabel; // @synthesize dispatchQueueLabel=_dispatchQueueLabel;
@property(readonly, nonatomic) NSString *threadName; // @synthesize threadName=_threadName;
@property(readonly, nonatomic) unsigned long long line; // @synthesize line=_line;
@property(readonly, nonatomic) NSString *function; // @synthesize function=_function;
@property(readonly, nonatomic) NSString *file; // @synthesize file=_file;
@property(readonly, nonatomic) NSString *formattedString; // @synthesize formattedString=_formattedString;
@property(readonly, nonatomic) NSString *format; // @synthesize format=_format;
@property(readonly, nonatomic) unsigned long long level; // @synthesize level=_level;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithLevel:(unsigned long long)arg1 format:(id)arg2 formattedString:(id)arg3 file:(id)arg4 function:(id)arg5 line:(unsigned long long)arg6 threadName:(id)arg7 dispatchQueueLabel:(id)arg8 callstack:(id)arg9 safeParameters:(id)arg10 logMetadata:(id)arg11;

@end

