//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBEnumArray;

@interface MLKITx_GMVBarcodeInitializationOptions : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPBEnumArray *formatArray; // @dynamic formatArray;
@property(readonly, nonatomic) unsigned long long formatArray_Count; // @dynamic formatArray_Count;

@end

