//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCTUploaderLock.h"

@class NSString, NSURL;

@interface MLKITx_CCTFileLock : NSObject <CCTUploaderLock>
{
    int _fd;
    NSURL *_file;
}

@property(nonatomic) int fd; // @synthesize fd=_fd;
@property(readonly, nonatomic) NSURL *file; // @synthesize file=_file;
- (void).cxx_destruct;
- (void)unlock;
- (_Bool)lock:(id *)arg1;
- (id)initWithFile:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

