//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_EXHApplicationResponse, NSMutableDictionary, NSString;

@interface MLKITx_EPIConfigurationSnapshot : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableDictionary *crossTokens; // @dynamic crossTokens;
@property(readonly, nonatomic) unsigned long long crossTokens_Count; // @dynamic crossTokens_Count;
@property(retain, nonatomic) NSMutableDictionary *flagOverrides; // @dynamic flagOverrides;
@property(readonly, nonatomic) unsigned long long flagOverrides_Count; // @dynamic flagOverrides_Count;
@property(nonatomic) long long flagsHash; // @dynamic flagsHash;
@property(nonatomic) _Bool hasFlagsHash; // @dynamic hasFlagsHash;
@property(nonatomic) _Bool hasHeterodyneResponse; // @dynamic hasHeterodyneResponse;
@property(nonatomic) _Bool hasObfuscatedGaiaId; // @dynamic hasObfuscatedGaiaId;
@property(nonatomic) _Bool hasServerConfigurationVersion; // @dynamic hasServerConfigurationVersion;
@property(nonatomic) _Bool hasSnapshotToken; // @dynamic hasSnapshotToken;
@property(nonatomic) _Bool hasSyncTimeSeconds; // @dynamic hasSyncTimeSeconds;
@property(retain, nonatomic) MLKITx_EXHApplicationResponse *heterodyneResponse; // @dynamic heterodyneResponse;
@property(copy, nonatomic) NSString *obfuscatedGaiaId; // @dynamic obfuscatedGaiaId;
@property(nonatomic) long long serverConfigurationVersion; // @dynamic serverConfigurationVersion;
@property(copy, nonatomic) NSString *snapshotToken; // @dynamic snapshotToken;
@property(nonatomic) long long syncTimeSeconds; // @dynamic syncTimeSeconds;

@end

