//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_FBMLModelOptions;

@interface MLKITx_FBMLOnDeviceObjectDetectorOptions : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) float classificationConfidenceThreshold; // @dynamic classificationConfidenceThreshold;
@property(nonatomic) _Bool classificationEnabled; // @dynamic classificationEnabled;
@property(retain, nonatomic) MLKITx_FBMLModelOptions *customLocalModelOptions; // @dynamic customLocalModelOptions;
@property(nonatomic) int detectorMode; // @dynamic detectorMode;
@property(nonatomic) _Bool hasClassificationConfidenceThreshold; // @dynamic hasClassificationConfidenceThreshold;
@property(nonatomic) _Bool hasClassificationEnabled; // @dynamic hasClassificationEnabled;
@property(nonatomic) _Bool hasCustomLocalModelOptions; // @dynamic hasCustomLocalModelOptions;
@property(nonatomic) _Bool hasDetectorMode; // @dynamic hasDetectorMode;
@property(nonatomic) _Bool hasMaxPerObjectLabelCount; // @dynamic hasMaxPerObjectLabelCount;
@property(nonatomic) _Bool hasMultipleObjectsEnabled; // @dynamic hasMultipleObjectsEnabled;
@property(nonatomic) unsigned int maxPerObjectLabelCount; // @dynamic maxPerObjectLabelCount;
@property(nonatomic) _Bool multipleObjectsEnabled; // @dynamic multipleObjectsEnabled;

@end

