//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_FBMLInferenceCommonLogEvent, NSMutableArray;

@interface MLKITx_FBMLOnDeviceSmartReplyLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int blacklistErrorCode; // @dynamic blacklistErrorCode;
@property(nonatomic) _Bool hasBlacklistErrorCode; // @dynamic hasBlacklistErrorCode;
@property(nonatomic) _Bool hasInferenceCommonLogEvent; // @dynamic hasInferenceCommonLogEvent;
@property(nonatomic) _Bool hasResultStatus; // @dynamic hasResultStatus;
@property(nonatomic) _Bool hasSuggestionsCount; // @dynamic hasSuggestionsCount;
@property(retain, nonatomic) MLKITx_FBMLInferenceCommonLogEvent *inferenceCommonLogEvent; // @dynamic inferenceCommonLogEvent;
@property(nonatomic) int resultStatus; // @dynamic resultStatus;
@property(retain, nonatomic) NSMutableArray *smartRepliesArray; // @dynamic smartRepliesArray;
@property(readonly, nonatomic) unsigned long long smartRepliesArray_Count; // @dynamic smartRepliesArray_Count;
@property(nonatomic) int suggestionsCount; // @dynamic suggestionsCount;

@end

