//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_FBMLModelOptions_ModelDownloadConditions : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool canDownloadInBackground; // @dynamic canDownloadInBackground;
@property(nonatomic) _Bool hasCanDownloadInBackground; // @dynamic hasCanDownloadInBackground;
@property(nonatomic) _Bool hasIsChargingRequired; // @dynamic hasIsChargingRequired;
@property(nonatomic) _Bool hasIsDeviceIdleRequired; // @dynamic hasIsDeviceIdleRequired;
@property(nonatomic) _Bool hasIsWifiRequired; // @dynamic hasIsWifiRequired;
@property(nonatomic) _Bool isChargingRequired; // @dynamic isChargingRequired;
@property(nonatomic) _Bool isDeviceIdleRequired; // @dynamic isDeviceIdleRequired;
@property(nonatomic) _Bool isWifiRequired; // @dynamic isWifiRequired;

@end

