//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_CCTLogContext, NSURL;

@interface MLKITx_CCTLogFile : NSObject
{
    struct stat _statInfo;
    MLKITx_CCTLogContext *_context;
    NSURL *_url;
}

@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) MLKITx_CCTLogContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long fileSize;
@property(readonly, nonatomic) long long creationTimeMilliseconds;
- (id)initWithContext:(id)arg1 url:(id)arg2;

@end

