//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MLKITx_GMVFeature.h"

@class MLKITx_GMVTextFeatureBox, NSArray, NSString;

@interface MLKITx_GMVTextElementFeature : MLKITx_GMVFeature
{
    NSString *_value;
    NSArray *_cornerPoints;
    MLKITx_GMVTextFeatureBox *_boundingBox;
    struct CGRect _rect;
}

@property(nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(readonly, copy) MLKITx_GMVTextFeatureBox *boundingBox; // @synthesize boundingBox=_boundingBox;
@property(readonly, copy) NSArray *cornerPoints; // @synthesize cornerPoints=_cornerPoints;
@property(readonly, copy) NSString *value; // @synthesize value=_value;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setTextFeatureBoundingBox:(id)arg1;
- (void)setDetectedCorners:(id)arg1;
- (void)setDetectedValue:(id)arg1;
- (void)setTextElementRect:(struct CGRect)arg1;
- (struct CGRect)bounds;
- (id)type;

@end

