//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_FBMLImageInfo, MLKITx_FBMLInferenceCommonLogEvent;

@interface MLKITx_FBMLOnDeviceTextDetectionLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasImageInfo; // @dynamic hasImageInfo;
@property(nonatomic) _Bool hasInferenceCommonLogEvent; // @dynamic hasInferenceCommonLogEvent;
@property(retain, nonatomic) MLKITx_FBMLImageInfo *imageInfo; // @dynamic imageInfo;
@property(retain, nonatomic) MLKITx_FBMLInferenceCommonLogEvent *inferenceCommonLogEvent; // @dynamic inferenceCommonLogEvent;

@end

