//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData;

@interface MLKITx_EXHParamPartitionTag : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasId_p; // @dynamic hasId_p;
@property(nonatomic) _Bool hasTag; // @dynamic hasTag;
@property(nonatomic) long long id_p; // @dynamic id_p;
@property(copy, nonatomic) NSData *tag; // @dynamic tag;

@end

