//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MLKITx_SRLMemoizingScope : NSObject
{
    struct unique_ptr<MLKITx_SRLMemoizingScopeIvars, std::__1::default_delete<MLKITx_SRLMemoizingScopeIvars>> _ivars;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)instanceForIdentifier:(struct _SRLImplementationRegistrationData *)arg1 factoryBlock:(CDUnknownBlockType)arg2;
- (id)init;

@end

