//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_BARRecognitionOptions, NSData;

@interface MLKITx_BARBarhopperRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int debugLevel; // @dynamic debugLevel;
@property(nonatomic) _Bool hasDebugLevel; // @dynamic hasDebugLevel;
@property(nonatomic) _Bool hasImage; // @dynamic hasImage;
@property(nonatomic) _Bool hasRecognitionOptions; // @dynamic hasRecognitionOptions;
@property(copy, nonatomic) NSData *image; // @dynamic image;
@property(retain, nonatomic) MLKITx_BARRecognitionOptions *recognitionOptions; // @dynamic recognitionOptions;

@end

