//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_FBMLFaceDetectorOptions : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int classificationMode; // @dynamic classificationMode;
@property(nonatomic) int contourMode; // @dynamic contourMode;
@property(nonatomic) _Bool hasClassificationMode; // @dynamic hasClassificationMode;
@property(nonatomic) _Bool hasContourMode; // @dynamic hasContourMode;
@property(nonatomic) _Bool hasIsTrackingEnabled; // @dynamic hasIsTrackingEnabled;
@property(nonatomic) _Bool hasLandmarkMode; // @dynamic hasLandmarkMode;
@property(nonatomic) _Bool hasMinFaceSize; // @dynamic hasMinFaceSize;
@property(nonatomic) _Bool hasPerformanceMode; // @dynamic hasPerformanceMode;
@property(nonatomic) _Bool isTrackingEnabled; // @dynamic isTrackingEnabled;
@property(nonatomic) int landmarkMode; // @dynamic landmarkMode;
@property(nonatomic) float minFaceSize; // @dynamic minFaceSize;
@property(nonatomic) int performanceMode; // @dynamic performanceMode;

@end

