//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_FBMLObjectInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int category; // @dynamic category;
@property(nonatomic) float classificationConfidence; // @dynamic classificationConfidence;
@property(nonatomic) _Bool hasCategory; // @dynamic hasCategory;
@property(nonatomic) _Bool hasClassificationConfidence; // @dynamic hasClassificationConfidence;
@property(nonatomic) _Bool hasLabelCount; // @dynamic hasLabelCount;
@property(nonatomic) _Bool hasTrackingId; // @dynamic hasTrackingId;
@property(nonatomic) unsigned int labelCount; // @dynamic labelCount;
@property(nonatomic) int trackingId; // @dynamic trackingId;

@end

