//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_FBMLOnDeviceLanguageIdentificationLogEvent_IdentifiedLanguage;

@interface MLKITx_FBMLOnDeviceLanguageIdentificationLogEvent_IdentifyLanguageResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasIdentifiedLanguage; // @dynamic hasIdentifiedLanguage;
@property(retain, nonatomic) MLKITx_FBMLOnDeviceLanguageIdentificationLogEvent_IdentifiedLanguage *identifiedLanguage; // @dynamic identifiedLanguage;

@end

