//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_FBMLDeleteModelLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasIsSuccessful; // @dynamic hasIsSuccessful;
@property(nonatomic) _Bool hasModelType; // @dynamic hasModelType;
@property(nonatomic) _Bool isSuccessful; // @dynamic isSuccessful;
@property(nonatomic) int modelType; // @dynamic modelType;

@end

