//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_FBMLModelOptions;

@interface MLKITx_FBMLOnDeviceImageLabelOptions : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) float confidenceThreshold; // @dynamic confidenceThreshold;
@property(retain, nonatomic) MLKITx_FBMLModelOptions *customLocalModelOptions; // @dynamic customLocalModelOptions;
@property(nonatomic) _Bool hasConfidenceThreshold; // @dynamic hasConfidenceThreshold;
@property(nonatomic) _Bool hasCustomLocalModelOptions; // @dynamic hasCustomLocalModelOptions;
@property(nonatomic) _Bool hasMaxLabels; // @dynamic hasMaxLabels;
@property(nonatomic) unsigned int maxLabels; // @dynamic maxLabels;

@end

