//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt32ObjectDictionary;

@interface MLKITx_EPILogSourceMapping : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPBInt32ObjectDictionary *entry; // @dynamic entry;
@property(readonly, nonatomic) unsigned long long entry_Count; // @dynamic entry_Count;

@end

