//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface MLKITx_FBMLTranslatorOptions : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasSourceLanguage; // @dynamic hasSourceLanguage;
@property(nonatomic) _Bool hasTargetLanguage; // @dynamic hasTargetLanguage;
@property(copy, nonatomic) NSString *sourceLanguage; // @dynamic sourceLanguage;
@property(copy, nonatomic) NSString *targetLanguage; // @dynamic targetLanguage;

@end

