//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface MLKITx_SRLImplementationConfiguration : NSObject <NSCopying>
{
    _Bool _required;
    id <SRLInstanceType> _instanceType;
}

@property(readonly, nonatomic, getter=isRequired) _Bool required; // @synthesize required=_required;
@property(readonly, nonatomic) id <SRLInstanceType> instanceType; // @synthesize instanceType=_instanceType;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)initWithConfigurationInstanceType:(id)arg1 required:(_Bool)arg2;

@end

