//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface MLKITx_BARBoardingPass : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *flightSegmentArray; // @dynamic flightSegmentArray;
@property(readonly, nonatomic) unsigned long long flightSegmentArray_Count; // @dynamic flightSegmentArray_Count;
@property(nonatomic) _Bool hasPassengerName; // @dynamic hasPassengerName;
@property(copy, nonatomic) NSString *passengerName; // @dynamic passengerName;

@end

