//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PHTHeterodyneSyncerProtocol.h"

@class MLKITx_GIPPseudonymousIDStore, MLKITx_PHTBreakableLock, MLKITx_PHTPhenotypeSyncAfterConfiguration, NSArray, NSObject<OS_dispatch_queue>, NSURL;

@interface MLKITx_PHTHeterodyneSyncer : NSObject <PHTHeterodyneSyncerProtocol>
{
    NSArray *_accounts;
    NSURL *_serverURL;
    _Bool _allowHTTP;
    id <CCTClockProtocol> _clock;
    MLKITx_GIPPseudonymousIDStore *_pseudonymousIDStore;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    MLKITx_PHTBreakableLock *_lock;
    MLKITx_PHTPhenotypeSyncAfterConfiguration *_syncAfterConfiguration;
    _Bool _debugForceSyncs;
}

+ (void)updateMetadataForCorruptionWithPackageName:(id)arg1 error:(id *)arg2;
+ (id)syncMetadataWithError:(id *)arg1;
@property(readonly, nonatomic) MLKITx_PHTPhenotypeSyncAfterConfiguration *syncAfterConfiguration; // @synthesize syncAfterConfiguration=_syncAfterConfiguration;
- (void).cxx_destruct;
- (_Bool)isInternalHeterodyneSyncer;
- (id)accountsWithLoggedOutAccount;
- (id)periodicTaskInfo;
- (_Bool)isNoInternetError:(id)arg1;
- (id)updateMetadataWithSyncedScopes:(id)arg1;
- (id)mergePartition:(id)arg1 withPartition:(id)arg2;
- (id)mergeResponse:(id)arg1 withResponse:(id)arg2;
- (id)createClientProperties:(id)arg1;
- (void)processResponse:(id)arg1 account:(id)arg2 syncedScopes:(id)arg3 requestedPackages:(id)arg4 requestError:(id)arg5 callback:(CDUnknownBlockType)arg6;
- (void)syncAccount:(id)arg1 syncedScopes:(id)arg2 fetchReason:(int)arg3 callback:(CDUnknownBlockType)arg4;
- (void)syncAllAccounts:(id)arg1 index:(long long)arg2 syncedScopes:(id)arg3 fetchReason:(int)arg4 heterodyneSyncInfo:(id)arg5 lastError:(id)arg6 callback:(CDUnknownBlockType)arg7;
- (void)syncWithCallback:(CDUnknownBlockType)arg1;
- (int)fetchReason:(id *)arg1;
- (id)initWithAccounts:(id)arg1 overrideServerURL:(id)arg2 allowHTTP:(_Bool)arg3 clock:(id)arg4 pseudonymousIDStore:(id)arg5 syncAfterConfiguration:(id)arg6 debugForceSyncs:(_Bool)arg7 callbackQueue:(id)arg8;

@end

