//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GIPLogFilter.h"

@class NSArray;

@interface MLKITx_GIPLogLogicalOrFilter : NSObject <GIPLogFilter>
{
    NSArray *_filters;
}

- (void).cxx_destruct;
- (_Bool)allowLogMessage:(id)arg1;
- (id)initWithFilters:(id)arg1;

@end

