//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_SRLMemoizingScope, NSDictionary, NSMutableDictionary;

@interface MLKITx_SRLRegistry : NSObject
{
    struct unique_ptr<MLKITx_SRLRegistryIvars, std::__1::default_delete<MLKITx_SRLRegistryIvars>> _ivars;
    NSDictionary *_protocolNameToAPIKey;
    NSMutableDictionary *_registrySingle;
    NSMutableDictionary *_registryMultiple;
    MLKITx_SRLMemoizingScope *_configScope;
}

+ (void)overrideSharedInstance:(id)arg1;
+ (id)sharedInstance;
@property(readonly, nonatomic) MLKITx_SRLMemoizingScope *configScope; // @synthesize configScope=_configScope;
@property(readonly, nonatomic) NSMutableDictionary *registryMultiple; // @synthesize registryMultiple=_registryMultiple;
@property(readonly, nonatomic) NSMutableDictionary *registrySingle; // @synthesize registrySingle=_registrySingle;
- (id).cxx_construct;
- (void).cxx_destruct;
- (CDUnknownBlockType)scopedBlock:(CDUnknownBlockType)arg1 forImplementationIdentifier:(struct _SRLImplementationRegistrationData *)arg2 apiScope:(unsigned char)arg3 implScope:(unsigned char)arg4 lifetime:(unsigned long long)arg5;
- (id)initPrivate;
- (void)dealloc;
- (id)description;
- (id)mutableCopy;
- (_Bool)isUsingComponentBindings;
- (void)registerBindingsForAPIData:(const struct _SRLAPIRegistrationData *)arg1 isComponentBinding:(_Bool)arg2;
- (const struct _SRLAPIRegistrationData *)registrationDataForAPI:(id)arg1;
- (_Bool)lazilyRegisterBindingsForAPIKey:(id)arg1;
- (void)internalRegisterBindings:(objc_metadata_hider_ptr_b6fcfd97)arg1;
@property(readonly, nonatomic) NSDictionary *protocolNameToAPIKey;
- (id)internalImplementationConfigForIdentifier:(struct _SRLImplementationRegistrationData *)arg1;
- (void)internalRegisterServiceAPI:(id)arg1 toImplementation:(id)arg2;
- (id)internalMultiBoundService:(id)arg1 earlGreyScopeTagSet:(id)arg2;
- (id)internalOptionalService:(id)arg1 earlGreyScopeTagSet:(id)arg2;
- (id)internalService:(id)arg1 earlGreyScopeTagSet:(id)arg2;
- (_Bool)internalHasImplementationForService:(id)arg1;
- (id)internalMultiBoundService:(id)arg1 scopeTags:(struct SRLScopeTagSet)arg2;
- (id)internalOptionalService:(id)arg1 scopeTags:(struct SRLScopeTagSet)arg2;
- (id)internalService:(id)arg1 scopeTags:(struct SRLScopeTagSet)arg2;
- (void)removeScopesWithTag:(id)arg1;
- (void)removeScopeWithAccountID:(id)arg1;
- (id)scopeWithTags:(struct SRLScopeTagSet)arg1;

@end

