//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_EXHParam_ExtensionValue, NSString;

@interface MLKITx_EXHParam : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool boolValue; // @dynamic boolValue;
@property(nonatomic) _Bool deleted; // @dynamic deleted;
@property(retain, nonatomic) MLKITx_EXHParam_ExtensionValue *extensionValue; // @dynamic extensionValue;
@property(nonatomic) double float64Value; // @dynamic float64Value;
@property(nonatomic) _Bool hasBoolValue; // @dynamic hasBoolValue;
@property(nonatomic) _Bool hasDeleted; // @dynamic hasDeleted;
@property(nonatomic) _Bool hasExtensionValue; // @dynamic hasExtensionValue;
@property(nonatomic) _Bool hasFloat64Value; // @dynamic hasFloat64Value;
@property(nonatomic) _Bool hasIntValue; // @dynamic hasIntValue;
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(nonatomic) _Bool hasParamStorageType; // @dynamic hasParamStorageType;
@property(nonatomic) _Bool hasStringValue; // @dynamic hasStringValue;
@property(nonatomic) _Bool hasValueType; // @dynamic hasValueType;
@property(nonatomic) long long intValue; // @dynamic intValue;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) int paramStorageType; // @dynamic paramStorageType;
@property(copy, nonatomic) NSString *stringValue; // @dynamic stringValue;
@property(nonatomic) int valueType; // @dynamic valueType;

@end

