//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_FBMLDurationStats : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) unsigned long long avgMs; // @dynamic avgMs;
@property(nonatomic) unsigned long long firstQuartileMs; // @dynamic firstQuartileMs;
@property(nonatomic) _Bool hasAvgMs; // @dynamic hasAvgMs;
@property(nonatomic) _Bool hasFirstQuartileMs; // @dynamic hasFirstQuartileMs;
@property(nonatomic) _Bool hasMaxMs; // @dynamic hasMaxMs;
@property(nonatomic) _Bool hasMedianMs; // @dynamic hasMedianMs;
@property(nonatomic) _Bool hasMinMs; // @dynamic hasMinMs;
@property(nonatomic) _Bool hasThirdQuartileMs; // @dynamic hasThirdQuartileMs;
@property(nonatomic) unsigned long long maxMs; // @dynamic maxMs;
@property(nonatomic) unsigned long long medianMs; // @dynamic medianMs;
@property(nonatomic) unsigned long long minMs; // @dynamic minMs;
@property(nonatomic) unsigned long long thirdQuartileMs; // @dynamic thirdQuartileMs;

@end

