//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_FBMLModelInfo, MLKITx_FBMLModelOptions_ModelDownloadConditions;

@interface MLKITx_FBMLModelOptions : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasInitialDownloadConditions; // @dynamic hasInitialDownloadConditions;
@property(nonatomic) _Bool hasIsModelUpdateEnabled; // @dynamic hasIsModelUpdateEnabled;
@property(nonatomic) _Bool hasModelInfo; // @dynamic hasModelInfo;
@property(nonatomic) _Bool hasUpdateDownloadConditions; // @dynamic hasUpdateDownloadConditions;
@property(retain, nonatomic) MLKITx_FBMLModelOptions_ModelDownloadConditions *initialDownloadConditions; // @dynamic initialDownloadConditions;
@property(nonatomic) _Bool isModelUpdateEnabled; // @dynamic isModelUpdateEnabled;
@property(retain, nonatomic) MLKITx_FBMLModelInfo *modelInfo; // @dynamic modelInfo;
@property(retain, nonatomic) MLKITx_FBMLModelOptions_ModelDownloadConditions *updateDownloadConditions; // @dynamic updateDownloadConditions;

@end

