//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_GMVPoint : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasX; // @dynamic hasX;
@property(nonatomic) _Bool hasY; // @dynamic hasY;
@property(nonatomic) int x; // @dynamic x;
@property(nonatomic) int y; // @dynamic y;

@end

