//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData, NSMutableArray, NSString;

@interface MLKITx_EXHExperimentIds : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSData *clearBlob; // @dynamic clearBlob;
@property(copy, nonatomic) NSString *clearBlobJs; // @dynamic clearBlobJs;
@property(retain, nonatomic) NSMutableArray *encryptedBlobArray; // @dynamic encryptedBlobArray;
@property(readonly, nonatomic) unsigned long long encryptedBlobArray_Count; // @dynamic encryptedBlobArray_Count;
@property(nonatomic) _Bool hasClearBlob; // @dynamic hasClearBlob;
@property(nonatomic) _Bool hasClearBlobJs; // @dynamic hasClearBlobJs;
@property(nonatomic) _Bool hasUsersMatch; // @dynamic hasUsersMatch;
@property(nonatomic) _Bool usersMatch; // @dynamic usersMatch;

@end

