//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface MLKITx_FBMLModelInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasHasLabelMap; // @dynamic hasHasLabelMap;
@property(nonatomic) _Bool hasHash_p; // @dynamic hasHash_p;
@property(nonatomic) _Bool hasLabelMap; // @dynamic hasLabelMap;
@property(nonatomic) _Bool hasModelType; // @dynamic hasModelType;
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(nonatomic) _Bool hasSize; // @dynamic hasSize;
@property(nonatomic) _Bool hasSource; // @dynamic hasSource;
@property(nonatomic) _Bool hasUri; // @dynamic hasUri;
@property(nonatomic) _Bool hasVersion; // @dynamic hasVersion;
@property(copy, nonatomic) NSString *hash_p; // @dynamic hash_p;
@property(nonatomic) int modelType; // @dynamic modelType;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) unsigned long long size; // @dynamic size;
@property(nonatomic) int source; // @dynamic source;
@property(copy, nonatomic) NSString *uri; // @dynamic uri;
@property(copy, nonatomic) NSString *version; // @dynamic version;

@end

