//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MLKITx_PHTSnapshot : NSObject
{
}

+ (_Bool)isValidFlagsHashInSnapshot:(id)arg1;
+ (long long)calculateFlagsHashForSnapshot:(id)arg1;
+ (id)paramToFlag:(id)arg1;
+ (id)emptyConfiguration:(id)arg1;
+ (id)snapshotToConfiguration:(id)arg1;
+ (id)committedSnapshotForPackage:(id)arg1 obfuscatedGaiaID:(id)arg2 error:(id *)arg3;
+ (id)uncommittedSnapshotForPackage:(id)arg1 obfuscatedGaiaID:(id)arg2 error:(id *)arg3;

@end

