//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_PHTPhenotypeFlags, NSArray;

@interface MLKITx_GMVLabelDetectorFlags : NSObject
{
    MLKITx_PHTPhenotypeFlags *_allFlags;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) MLKITx_PHTPhenotypeFlags *allFlags; // @synthesize allFlags=_allFlags;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *blacklist;
- (id)init;

@end

