//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface MLKITx_GMVBarcodeResultInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int format; // @dynamic format;
@property(nonatomic) _Bool hasFormat; // @dynamic hasFormat;
@property(nonatomic) _Bool hasValue; // @dynamic hasValue;
@property(nonatomic) _Bool hasValueFormat; // @dynamic hasValueFormat;
@property(copy, nonatomic) NSString *value; // @dynamic value;
@property(nonatomic) int valueFormat; // @dynamic valueFormat;

@end

