//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_FBMLInferenceCommonLogEvent, MLKITx_FBMLLanguageIdentificationOptions, MLKITx_FBMLOnDeviceLanguageIdentificationLogEvent_IdentifyLanguageResult, MLKITx_FBMLOnDeviceLanguageIdentificationLogEvent_IdentifyPossibleLanguagesResult;

@interface MLKITx_FBMLOnDeviceLanguageIdentificationLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasIdentifyLanguageResult; // @dynamic hasIdentifyLanguageResult;
@property(nonatomic) _Bool hasIdentifyPossibleLanguagesResult; // @dynamic hasIdentifyPossibleLanguagesResult;
@property(nonatomic) _Bool hasInferenceCommonLogEvent; // @dynamic hasInferenceCommonLogEvent;
@property(nonatomic) _Bool hasOptions; // @dynamic hasOptions;
@property(retain, nonatomic) MLKITx_FBMLOnDeviceLanguageIdentificationLogEvent_IdentifyLanguageResult *identifyLanguageResult; // @dynamic identifyLanguageResult;
@property(retain, nonatomic) MLKITx_FBMLOnDeviceLanguageIdentificationLogEvent_IdentifyPossibleLanguagesResult *identifyPossibleLanguagesResult; // @dynamic identifyPossibleLanguagesResult;
@property(retain, nonatomic) MLKITx_FBMLInferenceCommonLogEvent *inferenceCommonLogEvent; // @dynamic inferenceCommonLogEvent;
@property(retain, nonatomic) MLKITx_FBMLLanguageIdentificationOptions *options; // @dynamic options;

@end

