//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_PHTPhenotypeExperimentTokens, NSDictionary, NSString;

@interface MLKITx_PHTPhenotypeConfiguration : NSObject
{
    NSDictionary *_flags;
    NSString *_serverToken;
    NSString *_userID;
    MLKITx_PHTPhenotypeExperimentTokens *_tokens;
    long long _configurationVersion;
}

@property(readonly, nonatomic) long long configurationVersion; // @synthesize configurationVersion=_configurationVersion;
@property(readonly, nonatomic) MLKITx_PHTPhenotypeExperimentTokens *tokens; // @synthesize tokens=_tokens;
@property(readonly, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(readonly, nonatomic) NSString *serverToken; // @synthesize serverToken=_serverToken;
@property(readonly, nonatomic) NSDictionary *flags; // @synthesize flags=_flags;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithAllFlagsDictionary:(id)arg1 serverToken:(id)arg2 userID:(id)arg3 tokens:(id)arg4 configurationVersion:(long long)arg5;

@end

