//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_EPIBreakableLockData, NSFileManager, NSURL;

@interface MLKITx_PHTBreakableLock : NSObject
{
    NSURL *_file;
    id <GIPClock> _clock;
    NSFileManager *_fileManager;
    MLKITx_EPIBreakableLockData *_lockData;
}

- (void).cxx_destruct;
- (id)temporaryFileWithError:(id *)arg1;
- (id)fileLockData;
- (void)unlock;
- (_Bool)haveLock;
- (_Bool)lockWithError:(id *)arg1;
- (id)initWithFile:(id)arg1 clock:(id)arg2;

@end

