//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBEnumArray;

@interface MLKITx_FBMLRemoteConfigLogEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int HTTPResponseCode; // @dynamic HTTPResponseCode;
@property(nonatomic) unsigned long long durationMs; // @dynamic durationMs;
@property(retain, nonatomic) GPBEnumArray *handledErrorsArray; // @dynamic handledErrorsArray;
@property(readonly, nonatomic) unsigned long long handledErrorsArray_Count; // @dynamic handledErrorsArray_Count;
@property(nonatomic) _Bool hasDurationMs; // @dynamic hasDurationMs;
@property(nonatomic) _Bool hasHTTPResponseCode; // @dynamic hasHTTPResponseCode;
@property(retain, nonatomic) GPBEnumArray *partiallyHandledErrorsArray; // @dynamic partiallyHandledErrorsArray;
@property(readonly, nonatomic) unsigned long long partiallyHandledErrorsArray_Count; // @dynamic partiallyHandledErrorsArray_Count;
@property(retain, nonatomic) GPBEnumArray *unhandledErrorsArray; // @dynamic unhandledErrorsArray;
@property(readonly, nonatomic) unsigned long long unhandledErrorsArray_Count; // @dynamic unhandledErrorsArray_Count;

@end

