//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSMutableDictionary;

@interface MLKITx_EPILogSourceMapping_Entry : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *configPackageArray; // @dynamic configPackageArray;
@property(readonly, nonatomic) unsigned long long configPackageArray_Count; // @dynamic configPackageArray_Count;
@property(retain, nonatomic) NSMutableDictionary *externalExperimentIds; // @dynamic externalExperimentIds;
@property(readonly, nonatomic) unsigned long long externalExperimentIds_Count; // @dynamic externalExperimentIds_Count;

@end

