//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GPBMessage, MLKITx_CCTClearcutLogEvent;

@protocol MLKITx_CCTClearcutLogger <NSObject>
- (void)logWithBlock:(void (^)(MLKITx_CCTClearcutLogEvent *))arg1;
- (void)logWithExtension:(GPBMessage *)arg1;
- (void)log:(MLKITx_CCTClearcutLogEvent *)arg1;
- (MLKITx_CCTClearcutLogEvent *)newEvent;
@end

