//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt64Array;

@interface MLKITx_Int64ListParam : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPBInt64Array *elementArray; // @dynamic elementArray;
@property(readonly, nonatomic) unsigned long long elementArray_Count; // @dynamic elementArray_Count;

@end

