//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_ClientInfo, NSData, NSString;

@interface MLKITx_EXHClientProperties : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool authenticated; // @dynamic authenticated;
@property(retain, nonatomic) MLKITx_ClientInfo *clientInfo; // @dynamic clientInfo;
@property(copy, nonatomic) NSData *dogfoodToken; // @dynamic dogfoodToken;
@property(nonatomic) _Bool hasAuthenticated; // @dynamic hasAuthenticated;
@property(nonatomic) _Bool hasClientInfo; // @dynamic hasClientInfo;
@property(nonatomic) _Bool hasDogfoodToken; // @dynamic hasDogfoodToken;
@property(nonatomic) _Bool hasIsMaybeGooglerGmscore; // @dynamic hasIsMaybeGooglerGmscore;
@property(nonatomic) _Bool hasPseudonymousCookie; // @dynamic hasPseudonymousCookie;
@property(nonatomic) _Bool hasPseudonymousId; // @dynamic hasPseudonymousId;
@property(nonatomic) _Bool hasUserId; // @dynamic hasUserId;
@property(nonatomic) _Bool isMaybeGooglerGmscore; // @dynamic isMaybeGooglerGmscore;
@property(copy, nonatomic) NSString *pseudonymousCookie; // @dynamic pseudonymousCookie;
@property(nonatomic) long long pseudonymousId; // @dynamic pseudonymousId;
@property(nonatomic) long long userId; // @dynamic userId;

@end

