//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_GMVDownloadEvent, MLKITx_GMVImageAnalysisEvent, MLKITx_GMVInitializationEvent;

@interface MLKITx_GMVVisionExtension : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) MLKITx_GMVDownloadEvent *downloadEvent; // @dynamic downloadEvent;
@property(nonatomic) _Bool hasDownloadEvent; // @dynamic hasDownloadEvent;
@property(nonatomic) _Bool hasImageAnalysisEvent; // @dynamic hasImageAnalysisEvent;
@property(nonatomic) _Bool hasInitEvent; // @dynamic hasInitEvent;
@property(nonatomic) _Bool hasLibraryVersionCode; // @dynamic hasLibraryVersionCode;
@property(retain, nonatomic) MLKITx_GMVImageAnalysisEvent *imageAnalysisEvent; // @dynamic imageAnalysisEvent;
@property(retain, nonatomic) MLKITx_GMVInitializationEvent *initEvent; // @dynamic initEvent;
@property(nonatomic) int libraryVersionCode; // @dynamic libraryVersionCode;

@end

