//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSURL;

@interface MLKITx_CCTQosTierOverrides : NSObject
{
    NSURL *_logDirectory;
    NSDictionary *_overrides;
}

@property(retain, nonatomic) NSDictionary *overrides; // @synthesize overrides=_overrides;
@property(retain, nonatomic) NSURL *logDirectory; // @synthesize logDirectory=_logDirectory;
- (void).cxx_destruct;
- (id)overrideForLogSource:(long long)arg1;
- (void)loadFromFile;
- (id)initWithLogDirectory:(id)arg1;

@end

