//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCTClearcutAutoCountersDelegate.h"
#import "CCTClearcutMetaLoggerProtocol.h"

@class MLKITx_CCTClearcutAutoCounters, MLKITx_CCTClearcutFlags, MLKITx_CCTClearcutLogger, NSString;

@interface MLKITx_CCTClearcutMetaLogger : NSObject <CCTClearcutAutoCountersDelegate, CCTClearcutMetaLoggerProtocol>
{
    MLKITx_CCTClearcutLogger *_logger;
    MLKITx_CCTClearcutFlags *_flags;
    MLKITx_CCTClearcutAutoCounters *_autoCounters;
    id <CCTClockProtocol> _clock;
}

@property(retain, nonatomic) id <CCTClockProtocol> clock; // @synthesize clock=_clock;
@property(retain, nonatomic) MLKITx_CCTClearcutAutoCounters *autoCounters; // @synthesize autoCounters=_autoCounters;
@property(retain, nonatomic) MLKITx_CCTClearcutFlags *flags; // @synthesize flags=_flags;
@property(retain, nonatomic) MLKITx_CCTClearcutLogger *logger; // @synthesize logger=_logger;
- (void).cxx_destruct;
- (_Bool)isUnplugged;
- (int)qosTierFromContext:(id)arg1;
- (id)dimensionsOfContext:(id)arg1;
- (id)dimensionsForConnectionAndCharging;
- (void)flushCountersToLogger;
- (void)logUploadTime:(long long)arg1 endTime:(long long)arg2 error:(id)arg3;
- (void)logDeletingOverTTLLogFiles:(id)arg1;
- (void)logDeletingOverSizeLogFiles:(id)arg1;
- (void)logRequestUploadDelayWithCurrentTime:(long long)arg1 logFile:(id)arg2;
- (void)logResponse:(id)arg1 context:(id)arg2 startTime:(long long)arg3 finishTime:(long long)arg4;
- (void)logRequestContentLength:(id)arg1 request:(id)arg2;
- (void)logFilesWillBeUploaded:(id)arg1;
- (void)logCounters:(id)arg1;
- (long long)maxCounterCount;
- (_Bool)shouldLogCounters;
- (id)initWithLogger:(id)arg1 flags:(id)arg2 clock:(id)arg3;
- (id)initWithLogger:(id)arg1 flags:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

