//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MLKITx_PHTPhenotypeUtil : NSObject
{
}

+ (id)bundleNamespacedPackage:(id)arg1 multiCommitMode:(_Bool)arg2;
+ (_Bool)isMultiCommitPackage:(id)arg1;
+ (id)defaultPhenotypeDirectory;
+ (void)setDefaultDirectory:(id)arg1;
+ (_Bool)isPhenotypePackage:(id)arg1;
+ (id)phenotypePackageName;
+ (unsigned long long)intPow:(unsigned long long)arg1 power:(unsigned long long)arg2;
+ (unsigned long long)appVersionAsInteger:(id)arg1 withMajorWidth:(unsigned long long)arg2 minorWidth:(unsigned long long)arg3 patchWidth:(unsigned long long)arg4;
+ (unsigned long long)appVersionAsInteger:(id)arg1 withWidth:(unsigned long long)arg2;
+ (unsigned long long)appVersionAsIntegerWithMajorWidth:(unsigned long long)arg1 minorWidth:(unsigned long long)arg2 patchWidth:(unsigned long long)arg3;
+ (unsigned long long)appVersionAsIntegerWithWidth:(unsigned long long)arg1;
+ (_Bool)createDirectoryIfMissing:(id)arg1 error:(id *)arg2;
+ (id)uuid;

@end

