//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MLKITx_GMVBarcodeResultInfo, MLKITx_GMVBoundingPoly, MLKITx_GMVFaceResultInfo;

@interface MLKITx_GMVResultInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) MLKITx_GMVBarcodeResultInfo *barcodeResultInfo; // @dynamic barcodeResultInfo;
@property(retain, nonatomic) MLKITx_GMVBoundingPoly *bpoly; // @dynamic bpoly;
@property(retain, nonatomic) MLKITx_GMVFaceResultInfo *faceResultInfo; // @dynamic faceResultInfo;
@property(nonatomic) _Bool hasBarcodeResultInfo; // @dynamic hasBarcodeResultInfo;
@property(nonatomic) _Bool hasBpoly; // @dynamic hasBpoly;
@property(nonatomic) _Bool hasFaceResultInfo; // @dynamic hasFaceResultInfo;
@property(nonatomic) _Bool hasId_p; // @dynamic hasId_p;
@property(nonatomic) int id_p; // @dynamic id_p;

@end

