//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface MLKITx_FBMLOnDeviceLanguageIdentificationLogEvent_IdentifiedLanguage : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) float confidence; // @dynamic confidence;
@property(nonatomic) _Bool hasConfidence; // @dynamic hasConfidence;
@property(nonatomic) _Bool hasLanguageCode; // @dynamic hasLanguageCode;
@property(copy, nonatomic) NSString *languageCode; // @dynamic languageCode;

@end

