//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLKITx_FBMLLanguageIdentificationOptions : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) float confidenceThreshold; // @dynamic confidenceThreshold;
@property(nonatomic) _Bool hasConfidenceThreshold; // @dynamic hasConfidenceThreshold;
@property(nonatomic) _Bool hasIdentifyAllLanguagesConfidenceThreshold; // @dynamic hasIdentifyAllLanguagesConfidenceThreshold;
@property(nonatomic) _Bool hasIdentifyLanguageConfidenceThreshold; // @dynamic hasIdentifyLanguageConfidenceThreshold;
@property(nonatomic) float identifyAllLanguagesConfidenceThreshold; // @dynamic identifyAllLanguagesConfidenceThreshold;
@property(nonatomic) float identifyLanguageConfidenceThreshold; // @dynamic identifyLanguageConfidenceThreshold;

@end

