//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MLKITx_CCTClearcutFileUtility : NSObject
{
}

+ (id)directoryContents:(id)arg1;
+ (id)uploaderStateInLogDirectory:(id)arg1;
+ (id)uploaderLockFileInLogDirectory:(id)arg1;
+ (id)uploaderStateFileInLogDirectory:(id)arg1;
+ (_Bool)ensureLogDirectory:(id)arg1;
+ (id)defaultLogDirectory;
+ (void)setDefaultDirectory:(id)arg1;

@end

