//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MLKITx_GIPLogCallstack.h"

@class NSArray;

@interface MLKITx_GIPLogSymbolCallstack : MLKITx_GIPLogCallstack
{
    NSArray *_symbols;
}

+ (id)symbolCallstackIgnoringFrameCount:(unsigned long long)arg1;
@property(readonly, nonatomic) NSArray *symbols; // @synthesize symbols=_symbols;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithSymbols:(id)arg1;

@end

