//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MLKITx_GOOProvider : NSObject
{
    CDUnknownBlockType _block;
}

+ (id)providerWithBlock:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (id)get;
- (id)initWithBlock:(CDUnknownBlockType)arg1;

@end

