//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GIPLogFilter.h"

@interface MLKITx_GIPLogMininumLevelFilter : NSObject <GIPLogFilter>
{
    unsigned long long _minimumLevel;
}

- (_Bool)allowLogMessage:(id)arg1;
- (id)initWithMinimumLevel:(unsigned long long)arg1;

@end

