//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_FBMLModelOptions, NSString;

@interface MLKLocalModel : NSObject
{
    NSString *_path;
    MLKITx_FBMLModelOptions *_loggingProtoOptions;
}

@property(readonly, nonatomic) MLKITx_FBMLModelOptions *loggingProtoOptions; // @synthesize loggingProtoOptions=_loggingProtoOptions;
@property(readonly, copy, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (id)initWithPath:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;

@end

