//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class MLKITx_FBMLModelOptions_ModelDownloadConditions;

@interface MLKModelDownloadConditions : NSObject <NSCopying>
{
    _Bool _allowsCellularAccess;
    _Bool _allowsBackgroundDownloading;
    MLKITx_FBMLModelOptions_ModelDownloadConditions *_loggingProtoConditions;
}

@property(retain, nonatomic) MLKITx_FBMLModelOptions_ModelDownloadConditions *loggingProtoConditions; // @synthesize loggingProtoConditions=_loggingProtoConditions;
@property(nonatomic) _Bool allowsBackgroundDownloading; // @synthesize allowsBackgroundDownloading=_allowsBackgroundDownloading;
@property(nonatomic) _Bool allowsCellularAccess; // @synthesize allowsCellularAccess=_allowsCellularAccess;
- (void).cxx_destruct;
- (id)init;
- (id)initWithAllowsCellularAccess:(_Bool)arg1 allowsBackgroundDownloading:(_Bool)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;

@end

