//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GULUserDefaults;

@interface MLKModelPreferencesManager : NSObject
{
    GULUserDefaults *_userDefaults;
}

+ (id)sharedManager;
@property(readonly, nonatomic) GULUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
- (void).cxx_destruct;
- (id)userDefaultsKeyForModelInfo:(id)arg1 context:(id)arg2 name:(id)arg3;
- (void)saveAppVersion:(id)arg1 forIncompatibleModelInfo:(id)arg2 context:(id)arg3;
- (id)initWithUserDefaults:(id)arg1;
- (id)appVersionForIncompatibleModelInfo:(id)arg1 context:(id)arg2;
- (void)saveIncompatibleModelInfo:(id)arg1 context:(id)arg2;
- (id)modelHashForIncompatibleModelInfo:(id)arg1 context:(id)arg2;

@end

