//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSStreamDelegate.h"

@class NSInputStream, NSMutableData, NSObject<OS_dispatch_queue>, NSString;

@interface MLKModelHasher : NSObject <NSStreamDelegate>
{
    struct CC_SHA256state_st _context;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    CDUnknownBlockType _completion;
    NSInputStream *_iStream;
    NSMutableData *_readBuffer;
    CDUnknownBlockType _testBlock;
}

+ (id)fakeModelHasherWithSHA256Hash:(id)arg1 error:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType testBlock; // @synthesize testBlock=_testBlock;
@property(retain, nonatomic) NSMutableData *readBuffer; // @synthesize readBuffer=_readBuffer;
@property(retain, nonatomic) NSInputStream *iStream; // @synthesize iStream=_iStream;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
- (void).cxx_destruct;
- (void)hashMoreBytes;
- (void)finishWithError:(id)arg1;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (void)runWithFilePath:(id)arg1 callbackQueue:(id)arg2 completion:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

