//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKContext;

@interface MLKModelManager : NSObject
{
    MLKContext *_context;
}

+ (id)modelManagerForContext:(id)arg1;
+ (void)clearModelManagerInstances;
+ (id)modelManager;
+ (void)initialize;
@property(nonatomic) __weak MLKContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (id)initWithContext:(id)arg1;
- (void)deleteDownloadedModel:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)downloadModel:(id)arg1 conditions:(id)arg2;
- (_Bool)isModelDownloaded:(id)arg1;

@end

