//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_FBMLModelOptions, NSString, Protocol;

@interface MLKRemoteModel : NSObject
{
    NSString *_name;
    NSString *_identifier;
    Protocol *_protocol;
    MLKITx_FBMLModelOptions *_loggingProtoOptions;
}

@property(readonly, nonatomic) MLKITx_FBMLModelOptions *loggingProtoOptions; // @synthesize loggingProtoOptions=_loggingProtoOptions;
@property(readonly, nonatomic) Protocol *protocol; // @synthesize protocol=_protocol;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithName:(id)arg1 protocol:(id)arg2;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;

@end

