//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSNumber, NSString, NSURL;

@interface MLKRemoteModelInfo : NSObject
{
    NSString *_name;
    NSURL *_downloadURL;
    NSString *_sha256Hash;
    NSNumber *_size;
    NSDictionary *_inferenceInfo;
    NSDictionary *_requestHeaders;
    NSURL *_fallbackDownloadURL;
}

@property(copy, nonatomic) NSURL *fallbackDownloadURL; // @synthesize fallbackDownloadURL=_fallbackDownloadURL;
@property(copy, nonatomic) NSDictionary *requestHeaders; // @synthesize requestHeaders=_requestHeaders;
@property(copy, nonatomic) NSDictionary *inferenceInfo; // @synthesize inferenceInfo=_inferenceInfo;
@property(retain, nonatomic) NSNumber *size; // @synthesize size=_size;
@property(readonly, copy, nonatomic) NSString *sha256Hash; // @synthesize sha256Hash=_sha256Hash;
@property(readonly, copy, nonatomic) NSURL *downloadURL; // @synthesize downloadURL=_downloadURL;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)initWithName:(id)arg1 downloadURL:(id)arg2 sha256Hash:(id)arg3;

@end

