//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface MLKTextBlock : NSObject
{
    NSString *_text;
    NSArray *_lines;
    NSArray *_recognizedLanguages;
    NSArray *_cornerPoints;
    struct CGRect _frame;
}

@property(readonly, nonatomic) NSArray *cornerPoints; // @synthesize cornerPoints=_cornerPoints;
@property(readonly, nonatomic) NSArray *recognizedLanguages; // @synthesize recognizedLanguages=_recognizedLanguages;
@property(readonly, nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(readonly, nonatomic) NSArray *lines; // @synthesize lines=_lines;
@property(readonly, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (id)initWithTextBlockFeature:(id)arg1;

@end

