//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MLKITx_FBMLImageInfo, UIImage;

@interface MLKVisionImage : NSObject
{
    long long _orientation;
    MLKITx_FBMLImageInfo *_imageInfoProto;
    UIImage *_image;
    struct opaqueCMSampleBuffer *_sampleBuffer;
}

@property(readonly, nonatomic) struct opaqueCMSampleBuffer *sampleBuffer; // @synthesize sampleBuffer=_sampleBuffer;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
@property(readonly, nonatomic) MLKITx_FBMLImageInfo *imageInfoProto; // @synthesize imageInfoProto=_imageInfoProto;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (id)initWithImage:(id)arg1;

@end

