//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MLKVisionPoint : NSObject
{
    double _x;
    double _y;
}

@property(readonly, nonatomic) double y; // @synthesize y=_y;
@property(readonly, nonatomic) double x; // @synthesize x=_x;
- (id)initWithX:(double)arg1 y:(double)arg2;
- (_Bool)isEqual:(id)arg1;
- (id)description;

@end

