//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ZBarReaderViewController.h"

@class UIView;

@interface MyZBarViewReaderController : ZBarReaderViewController
{
    UIView *redLine;
    UIView *overlayBoxView;
    int scanMode;
    double _startX;
    double _startY;
    double _screenWidth;
    double _screenHeight;
}

- (void).cxx_destruct;
@property(nonatomic) double screenHeight; // @synthesize screenHeight=_screenHeight;
@property(nonatomic) double screenWidth; // @synthesize screenWidth=_screenWidth;
@property(nonatomic) double startY; // @synthesize startY=_startY;
@property(nonatomic) double startX; // @synthesize startX=_startX;
@property(nonatomic) int scanMode; // @synthesize scanMode;
- (unsigned long long)supportedInterfaceOrientations;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)changeOverlayFrame;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (id)scaleImageToSize:(struct CGSize)arg1 withImage:(id)arg2;
- (void)changeOverlayFrame:(long long)arg1 readerController:(id)arg2;
- (float)getStatusBarOffset;

@end

