//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface NativeStorage : CDVPlugin
{
}

- (void)keys:(id)arg1;
- (void)getItem:(id)arg1;
- (void)setItem:(id)arg1;
- (void)getString:(id)arg1;
- (void)putString:(id)arg1;
- (void)getDouble:(id)arg1;
- (void)putDouble:(id)arg1;
- (void)getInt:(id)arg1;
- (void)putInt:(id)arg1;
- (void)getBoolean:(id)arg1;
- (void)putBoolean:(id)arg1;
- (void)clear:(id)arg1;
- (void)remove:(id)arg1;

@end

