//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class WLReachability;

@interface NetworkDetector : CDVPlugin
{
    WLReachability *internetReach;
}

- (void).cxx_destruct;
- (id)deviceIPAdresses;
- (id)getPrimaryAddressWithIPv4:(id)arg1 andIPv6:(id)arg2;
- (void)getHWAddresses;
- (void)getIPAddresses;
- (void)initAddresses;
- (void)freeAddresses;
- (void)getNetworkInfo:(id)arg1;

@end

