//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (CordovaPreferences)
- (double)cordovaFloatSettingForKey:(id)arg1 defaultValue:(double)arg2;
- (_Bool)cordovaBoolSettingForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (id)cordovaSettingForKey:(id)arg1;
@end

