//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MLKITx_PHTPhenotypeExperimentTokens, MLKITx_PHTPhenotypeFlagsSnapshot, NSArray, NSData, NSNumber, NSString;

@protocol PHTBasePhenotypeFlagsProtocol
@property(readonly, nonatomic) long long configurationVersion;
@property(readonly, copy, nonatomic) NSString *serverToken;
@property(readonly, copy, nonatomic) NSString *packageName;
- (MLKITx_PHTPhenotypeFlagsSnapshot *)snapshot;
- (NSArray *)numberArrayForFlagName:(NSString *)arg1 withDefault:(NSArray *)arg2;
- (NSArray *)stringArrayForFlagName:(NSString *)arg1 withDefault:(NSArray *)arg2;
- (NSData *)dataForFlagName:(NSString *)arg1 defaultValue:(NSData *)arg2;
- (NSNumber *)numberForFlagName:(NSString *)arg1 defaultValue:(NSNumber *)arg2;
- (NSString *)stringForFlagName:(NSString *)arg1 defaultValue:(NSString *)arg2;
- (id)valueForFlagName:(NSString *)arg1 withDefault:(id)arg2;
@property(readonly, nonatomic) MLKITx_PHTPhenotypeExperimentTokens *tokens;
- (void)startLoading;
@end

