//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MLKITx_PHTPhenotypeSyncAfterConfiguration;

@protocol PHTHeterodyneSyncerProtocol
@property(readonly, nonatomic) MLKITx_PHTPhenotypeSyncAfterConfiguration *syncAfterConfiguration;
- (_Bool)isInternalHeterodyneSyncer;
- (void)syncWithCallback:(void (^)(_Bool, NSError *, _Bool, MLKITx_PHTHeterodyneSyncInfo *, MLKITx_PHTPeriodicTaskInfo *))arg1;
@end

