//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MLKITx_PHTPhenotype.h"
#import "PHTPhenotypeSyncAfter.h"

@class NSString;

@protocol PHTPhenotypeInternal <MLKITx_PHTPhenotype, PHTPhenotypeSyncAfter>
- (void)peekConfiguration:(NSString *)arg1 user:(NSString *)arg2 callback:(void (^)(MLKITx_PHTPhenotypeConfiguration *, NSError *))arg3;
- (_Bool)packageRegistered:(NSString *)arg1 error:(id *)arg2;
@end

