//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol PHTPhenotypeAccount <NSObject>
@property(readonly, nonatomic) NSString *email;
@property(readonly, nonatomic) NSString *obfuscatedGaiaID;
- (id <GTMFetcherAuthorizationProtocol>)authorization:(id *)arg1;
@end

