//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MLKITx_PHTPhenotype.h"

@class MLKITx_PHTPhenotypeSyncAfterConfiguration;

@protocol PHTPhenotypeSyncAfter <MLKITx_PHTPhenotype>
- (void)syncExperimentsWithServer:(id <PHTPhenotypeAccountService>)arg1 syncAfterConfiguration:(MLKITx_PHTPhenotypeSyncAfterConfiguration *)arg2 callback:(void (^)(_Bool, NSError *))arg3;
@end

