//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface PrivacyScreenPlugin : CDVPlugin
{
}

- (id)getImageName:(long long)arg1 delegate:(id)arg2 device:(CDStruct_e38957e0)arg3;
- (CDStruct_e38957e0)getCurrentDevice;
- (void)onAppDidEnterBackground:(id)arg1;
- (void)onAppWillEnterForeground:(id)arg1;
- (void)pluginInitialize;

@end

