//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface SecurityPlugin : CDVPlugin
{
}

- (void)enableOSNativeEncryption:(id)arg1;
- (void)hashData:(id)arg1;
- (void)base64Decode:(id)arg1;
- (void)base64Encode:(id)arg1;
- (void)localRandomString:(id)arg1;
- (void)decrypt:(id)arg1;
- (void)encrypt:(id)arg1;
- (void)keygen:(id)arg1;

@end

