//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SiriShareDataUtility : NSObject
{
}

+ (id)StrConvertToFullwidth:(id)arg1;
+ (_Bool)is16BitNumber:(id)arg1;
+ (_Bool)isHaveEnglish:(id)arg1;
+ (_Bool)isHaveChinese:(id)arg1;
+ (void)setSystemDate;
+ (void)dataSynchronize;
+ (id)getData:(id)arg1;
+ (void)saveData:(id)arg1 forKey:(id)arg2;
+ (void)removeData:(id)arg1;
+ (id)getUserDefaultsPkg;

@end

