//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class AVAudioEngine, SFSpeechAudioBufferRecognitionRequest, SFSpeechRecognitionTask, SFSpeechRecognizer;

@interface SpeechRecognition : CDVPlugin
{
    _Bool showPartialForIOS13_2;
    SFSpeechRecognizer *_speechRecognizer;
    AVAudioEngine *_audioEngine;
    SFSpeechAudioBufferRecognitionRequest *_recognitionRequest;
    SFSpeechRecognitionTask *_recognitionTask;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SFSpeechRecognitionTask *recognitionTask; // @synthesize recognitionTask=_recognitionTask;
@property(retain, nonatomic) SFSpeechAudioBufferRecognitionRequest *recognitionRequest; // @synthesize recognitionRequest=_recognitionRequest;
@property(retain, nonatomic) AVAudioEngine *audioEngine; // @synthesize audioEngine=_audioEngine;
@property(retain, nonatomic) SFSpeechRecognizer *speechRecognizer; // @synthesize speechRecognizer=_speechRecognizer;
- (void)requestPermission:(id)arg1;
- (void)hasPermission:(id)arg1;
- (void)getSupportedLanguages:(id)arg1;
- (void)stopListening:(id)arg1;
- (void)startListening:(id)arg1;
- (void)isRecognitionAvailable:(id)arg1;

@end

