//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TemperatureAndTint : NSObject
{
    float minTemperature;
    float maxTemperature;
    float tint;
    NSString *mode;
}

- (void).cxx_destruct;
@property(nonatomic) float tint; // @synthesize tint;
@property(nonatomic) float maxTemperature; // @synthesize maxTemperature;
@property(nonatomic) float minTemperature; // @synthesize minTemperature;
@property(retain, nonatomic) NSString *mode; // @synthesize mode;

@end

