//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class CDVInvokedUrlCommand, UIImage;

@interface Textocr : CDVPlugin
{
    CDVInvokedUrlCommand *_commandglo;
    UIImage *_image;
}

- (void).cxx_destruct;
@property(retain) UIImage *image; // @synthesize image=_image;
@property(retain) CDVInvokedUrlCommand *commandglo; // @synthesize commandglo=_commandglo;
- (id)retrieveAssetDataPhotosFramework:(id)arg1;
- (id)resizeImage:(id)arg1;
- (void)recText:(id)arg1;
- (void)downloadfromweb:(id)arg1;
- (void)download:(id)arg1;
- (void)checkPath:(id)arg1;
- (id)getScreenshot;
- (void)openURL:(id)arg1;
- (void)captureScreen:(id)arg1;
- (void)numberOCR:(id)arg1;
- (void)cardOCR:(id)arg1;

@end

