//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILocalNotification.h"

@interface UILocalNotification (APPLocalNotification)
- (unsigned long long)type;
- (_Bool)isRepeating;
- (_Bool)wasUpdated;
- (_Bool)isTriggered;
- (_Bool)isScheduled;
- (_Bool)wasInThePast;
- (id)encodeToJSON;
- (double)timeIntervalSinceLastTrigger;
- (double)timeIntervalSinceFireDate;
- (int)repeatIntervalInSeconds;
- (void)setOptions:(id)arg1;
- (id)getOptions;
- (id)options;
- (void)__init;
- (id)initWithOptions:(id)arg1;
@end

