//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UNUserNotificationCenter.h"

@class NSArray;

@interface UNUserNotificationCenter (APPLocalNotification)
- (void)cancelNotification:(id)arg1;
- (void)cancelAllNotifications;
- (void)clearNotification:(id)arg1;
- (void)clearAllNotifications;
- (id)getNotificationOptionsByType:(unsigned long long)arg1 andId:(id)arg2;
- (id)getNotificationOptionsById:(id)arg1;
- (id)getNotificationOptionsByType:(unsigned long long)arg1;
- (id)getNotificationOptions;
- (id)getNotificationWithId:(id)arg1 andType:(unsigned long long)arg2;
- (id)getNotificationWithId:(id)arg1;
- (_Bool)notificationExist:(id)arg1 type:(unsigned long long)arg2;
- (_Bool)notificationExist:(id)arg1;
- (id)getNotificationIdsByType:(unsigned long long)arg1;
@property(readonly, getter=getNotificationIds) NSArray *localNotificationIds;
- (id)getNotificationsByType:(unsigned long long)arg1;
- (id)getPendingNotifications;
- (id)getDeliveredNotifications;
@property(readonly, getter=getNotifications) NSArray *localNotifications;
@end

