//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIButton, UIImageView, UILabel, UIPanGestureRecognizer, UIPinchGestureRecognizer, UITapGestureRecognizer, UIView, UIViewController, UIWindow;

@interface VidyoWindow : NSObject
{
    _Bool _running;
    _Bool _mutemicphone;
    _Bool _mutecamera;
    _Bool _switchcamera;
    _Bool _faceBeautify;
    int _currAudioDevice;
    UIWindow *_boardWindow;
    UIView *_viewBackground;
    UIView *_viewTitlebar;
    UIView *_viewToolbar;
    UIImageView *_imageViewSignal;
    UILabel *_labelBandwidth;
    UIButton *_btnSpeaker;
    UIButton *_btnMute;
    UIButton *_btnEnableCamera;
    UIButton *_btnSwitchCamera;
    UIButton *_btnFaceBeautify;
    UIButton *_btnZoomVideo;
    UIButton *_btnHangup;
    UILabel *_timeView;
    UIViewController *_rootViewController;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UIPanGestureRecognizer *_panGestureRecognizer;
    UIPinchGestureRecognizer *_pinchGestureRecognizer;
    long long _timeBegin;
    struct CGPoint _centerOfWindow;
    struct CGPoint _centerOfScreen;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGPoint centerOfScreen; // @synthesize centerOfScreen=_centerOfScreen;
@property(nonatomic) struct CGPoint centerOfWindow; // @synthesize centerOfWindow=_centerOfWindow;
@property(nonatomic) long long timeBegin; // @synthesize timeBegin=_timeBegin;
@property(nonatomic) _Bool faceBeautify; // @synthesize faceBeautify=_faceBeautify;
@property(nonatomic) _Bool switchcamera; // @synthesize switchcamera=_switchcamera;
@property(nonatomic) _Bool mutecamera; // @synthesize mutecamera=_mutecamera;
@property(nonatomic) _Bool mutemicphone; // @synthesize mutemicphone=_mutemicphone;
@property(nonatomic) int currAudioDevice; // @synthesize currAudioDevice=_currAudioDevice;
@property(nonatomic) _Bool running; // @synthesize running=_running;
@property(retain, nonatomic) UIPinchGestureRecognizer *pinchGestureRecognizer; // @synthesize pinchGestureRecognizer=_pinchGestureRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) UILabel *timeView; // @synthesize timeView=_timeView;
@property(retain, nonatomic) UIButton *btnHangup; // @synthesize btnHangup=_btnHangup;
@property(retain, nonatomic) UIButton *btnZoomVideo; // @synthesize btnZoomVideo=_btnZoomVideo;
@property(retain, nonatomic) UIButton *btnFaceBeautify; // @synthesize btnFaceBeautify=_btnFaceBeautify;
@property(retain, nonatomic) UIButton *btnSwitchCamera; // @synthesize btnSwitchCamera=_btnSwitchCamera;
@property(retain, nonatomic) UIButton *btnEnableCamera; // @synthesize btnEnableCamera=_btnEnableCamera;
@property(retain, nonatomic) UIButton *btnMute; // @synthesize btnMute=_btnMute;
@property(retain, nonatomic) UIButton *btnSpeaker; // @synthesize btnSpeaker=_btnSpeaker;
@property(retain, nonatomic) UILabel *labelBandwidth; // @synthesize labelBandwidth=_labelBandwidth;
@property(retain, nonatomic) UIImageView *imageViewSignal; // @synthesize imageViewSignal=_imageViewSignal;
@property(retain, nonatomic) UIView *viewToolbar; // @synthesize viewToolbar=_viewToolbar;
@property(retain, nonatomic) UIView *viewTitlebar; // @synthesize viewTitlebar=_viewTitlebar;
@property(retain, nonatomic) UIView *viewBackground; // @synthesize viewBackground=_viewBackground;
@property(retain, nonatomic) UIWindow *boardWindow; // @synthesize boardWindow=_boardWindow;
- (void)stopRunning;
- (void)startRunning;
- (void)updateAudioDevice:(int)arg1;
- (void)updateOrientation;
- (void)updateStatInfo:(id)arg1;
- (void)showVideoWindows;
- (void)zoomInWindow;
- (void)zoomOutWindow;
- (void)hideWindow;
- (void)showWindow;
- (void)proximityStateDidChange;
- (void)stopPreview;
- (void)buttonAction:(id)arg1;
- (void)tapSubWindow:(id)arg1;
- (void)tapView:(id)arg1;
- (void)pinchView:(id)arg1;
- (void)panView:(id)arg1;
- (void)createSubWindows;
- (void)createTitlebar;
- (struct CGPoint)getScreenCenter;
- (struct CGRect)getScreenRect;
- (float)getScreenHeight;
- (float)getScreenWidth;
- (void)createToolbar;
- (id)init;

@end

