//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUImageView.h"

@class NSString, UILabel;

@interface VidyoWindowView : GPUImageView
{
    struct CGPoint _beginPoint;
    struct CGPoint _selfBeginCenter;
    NSString *_userURI;
    UILabel *_nameView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *nameView; // @synthesize nameView=_nameView;
@property(nonatomic) NSString *userURI; // @synthesize userURI=_userURI;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)updateImageEx:(id)arg1;
- (void)updateImage:(id)arg1;

@end

