//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WLImpl;

@interface WL : NSObject
{
    WLImpl *_wlImpl;
}

+ (id)sharedInstance;
@property(retain, nonatomic) WLImpl *wlImpl; // @synthesize wlImpl=_wlImpl;
- (void).cxx_destruct;
- (void)updateIonicBaseServerPath:(id)arg1 webView:(id)arg2;
- (id)serverUrl;
- (void)setServerUrl:(id)arg1;
- (void)removeActionReceiver:(id)arg1;
- (void)addActionReceiver:(id)arg1;
- (void)sendActionToJS:(id)arg1 withData:(id)arg2;
- (void)sendActionToJS:(id)arg1;
- (void)hideSplashScreen;
- (void)showSplashScreen;
- (id)mainHtmlFilePath;
- (void)initializeWebFrameworkWithDelegate:(id)arg1;
- (id)init;

@end

