//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class NSMutableDictionary;

@interface WLActionSenderPlugin : CDVPlugin
{
    NSMutableDictionary *_actionReceivers;
}

@property(retain, nonatomic) NSMutableDictionary *actionReceivers; // @synthesize actionReceivers=_actionReceivers;
- (void).cxx_destruct;
- (void)dispose;
- (void)sendActionToNative:(id)arg1;
- (void)removeActionReceiverIfExists:(id)arg1;
- (void)removeActionReceiver:(id)arg1;
- (void)addActionReceiver:(id)arg1;
- (void)pluginInitialize;

@end

