//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WLActionReceiver.h"

@class NSString;

@interface WLActionReceiverForCordova : NSObject <WLActionReceiver>
{
    NSString *_receiverId;
    id <CDVCommandDelegate> _commandDelegate;
    NSString *_callbackId;
}

@property(retain, nonatomic) NSString *callbackId; // @synthesize callbackId=_callbackId;
@property(retain, nonatomic) id <CDVCommandDelegate> commandDelegate; // @synthesize commandDelegate=_commandDelegate;
@property(retain, nonatomic) NSString *receiverId; // @synthesize receiverId=_receiverId;
- (void).cxx_destruct;
- (void)releaseCommandDelegate;
- (void)onActionReceived:(id)arg1 withData:(id)arg2;
- (id)initWithReceiverId:(id)arg1 commandDelegate:(id)arg2 callbackId:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

