//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface WLActionSender : NSObject
{
    NSMutableArray *_wlActionCacheForNative;
    NSMutableArray *_wlActionCacheForWeb;
    NSMutableArray *_webActionReceiverWrappers;
    NSMutableArray *_nativeActionReceiverWrappers;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *nativeActionReceiverWrappers; // @synthesize nativeActionReceiverWrappers=_nativeActionReceiverWrappers;
@property(retain, nonatomic) NSMutableArray *webActionReceiverWrappers; // @synthesize webActionReceiverWrappers=_webActionReceiverWrappers;
@property(retain, nonatomic) NSMutableArray *wlActionCacheForWeb; // @synthesize wlActionCacheForWeb=_wlActionCacheForWeb;
@property(retain, nonatomic) NSMutableArray *wlActionCacheForNative; // @synthesize wlActionCacheForNative=_wlActionCacheForNative;
- (void).cxx_destruct;
- (void)dispatchWLActionAsync:(id)arg1 toReceiverInternal:(id)arg2;
- (void)sendAction:(id)arg1 toReceiverWrappersArray:(id)arg2 ifUnsentCacheIn:(id)arg3;
- (void)sendActionToNative:(id)arg1;
- (void)sendActionToJS:(id)arg1;
- (void)removeActionReceiverWrapper:(id)arg1 fromWrappersArray:(id)arg2;
- (void)removeActionReceiver:(id)arg1 isJSActionReceiver:(_Bool)arg2;
- (_Bool)shouldDeliverAction:(id)arg1 toReceiver:(id)arg2;
- (void)tryToSendCachedActions:(id)arg1 toReceiver:(id)arg2;
- (void)addActionReceiver:(id)arg1 isJSActionReceiver:(_Bool)arg2 withTag:(id)arg3;
- (id)init;

@end

