//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@interface WLAuthorizationManagerPlugin : CDVPlugin
{
}

- (id)buildFailResponse:(id)arg1 withError:(id)arg2;
- (void)logout:(id)arg1;
- (void)setHeartBeatInterval:(id)arg1;
- (void)updateServerRelativeTime:(id)arg1;
- (void)setAuthorizationServerUrl:(id)arg1;
- (void)getAuthorizationServerUrl:(id)arg1;
- (void)setLoginTimeout:(id)arg1;
- (void)deleteCachedScopeByResource:(id)arg1;
- (void)cacheScopeByResource:(id)arg1;
- (void)getCachedScopeByResource:(id)arg1;
- (void)deleteAllAuthData:(id)arg1;
- (void)invokeAuthorizationRequestForScope:(id)arg1;
- (id)buildAccessTokenAsDictionary:(id)arg1;
- (void)getCachedAccessToken:(id)arg1;
- (void)clearAccessToken:(id)arg1;
- (void)getClientIdOrInvokeRegistration:(id)arg1;

@end

