//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WLDirectUpdateDownloaderUsingNSURL;

@interface WLDirectUpdateManager : NSObject
{
    _Bool _downloadDidStart;
    WLDirectUpdateDownloaderUsingNSURL *_wlDirectUpdateDownloader;
}

+ (id)sharedInstance;
@property _Bool downloadDidStart; // @synthesize downloadDidStart=_downloadDidStart;
@property(retain, nonatomic) WLDirectUpdateDownloaderUsingNSURL *wlDirectUpdateDownloader; // @synthesize wlDirectUpdateDownloader=_wlDirectUpdateDownloader;
- (void).cxx_destruct;
- (_Bool)shouldStartFreshDownload:(long long)arg1;
- (void)stop;
- (void)startWithDelegate:(id)arg1 updateFileURL:(id)arg2 updateFileTotalSize:(long long)arg3 updateUnpackedSize:(long long)arg4 updateChecksum:(long long)arg5 resumeDownload:(_Bool)arg6;
- (id)buildDirectUpdateFullURL:(id)arg1 updateURL:(id)arg2;
- (id)init;

@end

