//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol WLDirectUpdateDelegate <NSObject>
- (void)updateDidFinish:(int)arg1;
- (void)updateDidProgress:(int)arg1:(long long)arg2:(long long)arg3;
- (void)updateDidStart:(long long)arg1;
@end

