//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WLDirectUpdateDelegate.h"

@class CDVInvokedUrlCommand, NSString;

@interface WLDirectUpdatePluginCallbackContext : NSObject <WLDirectUpdateDelegate>
{
    id <WLDirectUpdatePluginCallbackDelegate> delegate;
    CDVInvokedUrlCommand *command;
}

@property(retain, nonatomic) CDVInvokedUrlCommand *command; // @synthesize command;
@property(nonatomic) __weak id <WLDirectUpdatePluginCallbackDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)updateDidFinish:(int)arg1;
- (void)updateDidProgress:(int)arg1:(long long)arg2:(long long)arg3;
- (void)updateDidStart:(long long)arg1;
- (id)initWithDelegate:(id)arg1 command:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

