//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDVInvokedUrlCommand;

@protocol WLDirectUpdatePluginCallbackDelegate <NSObject>
- (void)updateDidFinishWithCommand:(CDVInvokedUrlCommand *)arg1 status:(int)arg2;
- (void)updateDidProgressWithCommand:(CDVInvokedUrlCommand *)arg1 status:(int)arg2 totalSize:(long long)arg3 completedSize:(long long)arg4;
- (void)updateDidStartWithCommand:(CDVInvokedUrlCommand *)arg1 totalSize:(long long)arg2;
@end

