//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WLDirectUpdateDownloaderUsingNSURL : NSObject
{
    float base64fileLength;
    id <WLDirectUpdateDelegate> wlDirectUpdateDelegate;
    NSString *_fullURLAddress;
}

@property(retain, nonatomic) NSString *fullURLAddress; // @synthesize fullURLAddress=_fullURLAddress;
@property float base64fileLength; // @synthesize base64fileLength;
@property(retain, nonatomic) id <WLDirectUpdateDelegate> wlDirectUpdateDelegate; // @synthesize wlDirectUpdateDelegate;
- (void).cxx_destruct;
- (_Bool)copyFileWithSourceFile:(id)arg1 toFile:(id)arg2;
- (_Bool)copyListCordova:(id)arg1 fromFolder:(id)arg2 toFolder:(id)arg3;
- (_Bool)copyList:(id)arg1 fromFolder:(id)arg2 toFolder:(id)arg3;
- (id)parseDDUScriptFile:(id)arg1;
- (_Bool)handleDeltaUpdateWithWWWDirectory:(id)arg1 andTempWWWDirectory:(id)arg2;
- (long long)tempUpdateFileLength;
- (_Bool)writeToTempUpdateFile:(id)arg1;
- (_Bool)handleCancelDownload;
- (void)handleUpdateError:(int)arg1;
- (void)dispatchUpdateStatusInBackground:(CDUnknownBlockType)arg1;
- (void)logInvalidUpdateFileData;
- (void)stripFileLengthFromUpdateData:(id)arg1;
- (void)handleUpdateFileTampering:(id)arg1 updateFile:(id)arg2 replacementLogMessage:(id)arg3;
- (_Bool)validateUpdateFileIntegrity:(id)arg1 tempUpdateFileUsedToCreateUpdateZip:(id)arg2;
- (void)installUpdate;
- (_Bool)unzipUpdatedApplicationPackage:(id)arg1 toTempDirectory:(id)arg2;
- (id)tempUpdateFilePath;
- (void)sendDownloadRequestWithStartIndex:(long long)arg1;
- (void)sendDownloadRequestWithResumeData:(id)arg1;
- (void)sendDownloadRequest;
- (void)downloadUpdateWithDelegate:(id)arg1:(id)arg2:(long long)arg3:(long long)arg4:(_Bool)arg5:(_Bool)arg6;
- (void)stopDownload;
- (id)init;

@end

