//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WLImpl : NSObject
{
    _Bool _wlInitDidCompleteSuccessfully;
    _Bool splashShowing;
    id <WLInitWebFrameworkDelegate> _delegate;
}

+ (id)wwwFolderName;
+ (void)resetWebResourcesSharedDefaults;
+ (id)checksumFromPath:(id)arg1;
+ (long long)getFreeSpaceOnDevice;
+ (void)registerUserAgent;
+ (id)certificatePath;
+ (id)startPage;
+ (void)setAppChecksumWWWPath:(id)arg1;
+ (id)pathForResource:(id)arg1;
+ (id)readPrePackagedChecksum;
+ (_Bool)shouldExtractResourcesZip;
@property(retain, nonatomic) id <WLInitWebFrameworkDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isSplashShowing) _Bool splashShowing; // @synthesize splashShowing;
@property _Bool wlInitDidCompleteSuccessfully; // @synthesize wlInitDidCompleteSuccessfully=_wlInitDidCompleteSuccessfully;
- (void).cxx_destruct;
- (id)mainHtmlFilePath;
- (void)decryptZipFile:(id)arg1;
- (void)saveDefaultWLHost;
- (_Bool)extractZipFile;
- (_Bool)isFirstLaunchAfterInstallOrUpgrade;
- (void)deleteOldWWWFiles;
- (id)oldWWWDirName;
- (void)hideSplashScreen;
- (void)showSplashScreen;
- (void)initWL;
- (void)_wlInitDidCompleteWithResult:(id)arg1;
- (void)wlInitDidCompleteWithStatusCode:(long long)arg1 message:(id)arg2 data:(id)arg3;
- (void)wlInitDidCompleteWithStatusCode:(long long)arg1 message:(id)arg2;
- (void)initializeWebFrameworkWithDelegate:(id)arg1;
- (id)init;

@end

