//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WLNativeXHRSender : NSObject
{
    CDUnknownBlockType _requestFinishedBlock;
    NSString *_callbackId;
}

@property(retain, nonatomic) NSString *callbackId; // @synthesize callbackId=_callbackId;
@property(copy) CDUnknownBlockType requestFinishedBlock; // @synthesize requestFinishedBlock=_requestFinishedBlock;
- (void).cxx_destruct;
- (void)processResponseUsingRequest:(id)arg1 error:(id)arg2;
- (void)processLargeResponse;
- (void)requestRedirected:(id)arg1;
- (void)requestFailed:(id)arg1 error:(id)arg2;
- (void)requestFinished:(id)arg1;
- (void)sendRequestWithOptions:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;

@end

