//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel, UIProgressView;

@interface WLProgressView : UIView
{
    double progressViewVerticalPositionOffsetFactor;
    double statusLabelVerticalPositionOffset;
    UIProgressView *progressBar;
    UILabel *statusLabel;
    struct CGSize progressViewResizeRatio;
    struct CGSize progressBarResizeRatio;
}

@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel;
@property(retain, nonatomic) UIProgressView *progressBar; // @synthesize progressBar;
@property(nonatomic) double statusLabelVerticalPositionOffset; // @synthesize statusLabelVerticalPositionOffset;
@property(nonatomic) struct CGSize progressBarResizeRatio; // @synthesize progressBarResizeRatio;
@property(nonatomic) double progressViewVerticalPositionOffsetFactor; // @synthesize progressViewVerticalPositionOffsetFactor;
@property(nonatomic) struct CGSize progressViewResizeRatio; // @synthesize progressViewResizeRatio;
- (void).cxx_destruct;
- (void)hide;
- (void)orientationChanged:(id)arg1;
- (void)resizeView;
- (id)initWithParentView:(id)arg1;

@end

