//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView;

@interface WLSplashView : UIView
{
    _Bool visible;
    UIImageView *imageView;
    NSString *currentImageName;
}

@property(nonatomic) _Bool visible; // @synthesize visible;
@property(retain, nonatomic) NSString *currentImageName; // @synthesize currentImageName;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
- (void).cxx_destruct;
- (void)updateBounds;
- (_Bool)deviceIsIPad;
- (_Bool)deviceIsIPhone5;
- (long long)getStatusBarOrientation;
- (id)imageNameFromLaunchImages;
- (void)updateImage;
- (void)destroyViews;
- (void)detachFromParentView;
- (void)createImageView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)hide;
- (void)show;
- (id)initWithFrame:(struct CGRect)arg1;

@end

