//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "WTArchitectViewDebugDelegate.h"
#import "WTArchitectViewDelegate.h"

@class NSString, WTArchitectStartupConfiguration, WTArchitectView, WTNavigation;

@interface WTArchitectViewController : UIViewController <UIGestureRecognizerDelegate, WTArchitectViewDelegate, WTArchitectViewDebugDelegate>
{
    _Bool _startSDKAfterAppResume;
    id <WTArchitectViewControllerDelegate> _architectDelegate;
    WTArchitectView *_architectView;
    WTArchitectStartupConfiguration *_startupConfiguration;
    WTNavigation *_currentArchitectWorldNavigation;
    unsigned long long _supportedInterfaceOrientationsMask;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long supportedInterfaceOrientationsMask; // @synthesize supportedInterfaceOrientationsMask=_supportedInterfaceOrientationsMask;
@property(nonatomic) _Bool startSDKAfterAppResume; // @synthesize startSDKAfterAppResume=_startSDKAfterAppResume;
@property(retain, nonatomic) WTNavigation *currentArchitectWorldNavigation; // @synthesize currentArchitectWorldNavigation=_currentArchitectWorldNavigation;
@property(retain, nonatomic) WTArchitectStartupConfiguration *startupConfiguration; // @synthesize startupConfiguration=_startupConfiguration;
@property(retain, nonatomic) WTArchitectView *architectView; // @synthesize architectView=_architectView;
@property(nonatomic) __weak id <WTArchitectViewControllerDelegate> architectDelegate; // @synthesize architectDelegate=_architectDelegate;
- (void)didSwipeBack:(id)arg1;
- (void)didReceiveDeviceDidBecomeActiveNotification:(id)arg1;
- (void)didReceiveDeviceWillResignActiveNotification:(id)arg1;
- (void)architectView:(id)arg1 didEncounterInternalError:(id)arg2;
- (void)architectView:(id)arg1 didEncounterInternalWarning:(id)arg2;
- (void)architectViewFinishedDeviceSensorsCalibration:(id)arg1;
- (void)architectViewNeedsDeviceSensorCalibration:(id)arg1;
- (void)architectView:(id)arg1 willPresentViewController:(id)arg2 onViewController:(id)arg3;
- (id)presentingViewControllerForViewControllerPresentationInArchitectView:(id)arg1;
- (void)architectView:(id)arg1 didFailCaptureScreenWithError:(id)arg2;
- (void)architectView:(id)arg1 didCaptureScreenWithContext:(id)arg2;
- (void)architectView:(id)arg1 receivedJSONObject:(id)arg2;
- (void)architectView:(id)arg1 invokedURL:(id)arg2;
- (void)architectView:(id)arg1 didFailToLoadArchitectWorldNavigation:(id)arg2 withError:(id)arg3;
- (void)architectView:(id)arg1 didFinishLoadArchitectWorldNavigation:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)prefersStatusBarHidden;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 motionManager:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

