//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SRWebSocketDelegate.h"

@class NSString;

@interface XChatKit : NSObject <SRWebSocketDelegate>
{
}

- (void)WebSocketThread:(void *)arg1;
- (void)webSocket:(id)arg1 didCloseWithCode:(long long)arg2 reason:(id)arg3 wasClean:(_Bool)arg4;
- (void)webSocket:(id)arg1 didReceivePong:(id)arg2;
- (void)webSocket:(id)arg1 didReceiveMessageWithString:(id)arg2;
- (void)handleMsgOnMainThread:(void *)arg1;
- (void)webSocket:(id)arg1 didFailWithError:(id)arg2;
- (void)webSocketDidOpen:(id)arg1;
- (void)openWebSocket;
- (id)GetView;
- (id)GetWindow;
- (void)ZoomoutWindow;
- (void)ZoominWindow;
- (void)HideWindow;
- (void)ShowWindow;
- (void)SetVideoPreference:(int)arg1;
- (void)SetForeground;
- (void)SetBackground;
- (void)RetrieveVidyoCall;
- (void)HoldVidyoCall;
- (void)LeaveConference;
- (void)JoinConference:(id)arg1;
- (void)UploadLogs;
- (void)UploaLogsThread:(void *)arg1;
- (void)SendMessage:(id)arg1;
- (id)initXChatKit;
- (void)UploadToken;
- (void)audioRouteChanged:(id)arg1;
- (void)startMotionManager;
- (void)ActiveUserThread:(void *)arg1;
- (void)StatInfoThread:(void *)arg1;
- (void)updateActiveUserOnMainThread:(void *)arg1;
- (void)drawDashLine:(id)arg1 lineLength:(int)arg2 lineSpacing:(int)arg3 lineColor:(id)arg4;
- (void)updateOrientationOnMainThread:(void *)arg1;
- (void)updateStatInfoOnMainThread:(void *)arg1;
- (void)renderViewOnMainThread:(void *)arg1;
- (void)delViewOnMainThread:(void *)arg1;
- (void)setViewOnMainThread:(void *)arg1;
- (void)stopVidyoOnMainThread:(void *)arg1;
- (void)OnEventConferenceActive:(void *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

