//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class NSString;

@interface XChatPlugin : CDVPlugin
{
    NSString *_callbackId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *callbackId; // @synthesize callbackId=_callbackId;
- (void)onMakeCallViaSIPWithWss:(id)arg1 fromUser:(id)arg2;
- (void)onMakeCallViaVidyoWithWss:(id)arg1 fromUser:(id)arg2;
- (void)onJoinVidyoRoomWithWss:(id)arg1 fromUser:(id)arg2 connid:(id)arg3;
- (void)onDeleteVidyoRoomWithWss:(id)arg1 fromUser:(id)arg2 connid:(id)arg3;
- (void)onCreateVidyoRoomWithWss:(id)arg1 fromUser:(id)arg2;
- (void)onSendMessageWithWss:(id)arg1 fromUser:(id)arg2 connid:(id)arg3;
- (void)onJoinVidyoRoom:(id)arg1;
- (void)onDeleteVidyoRoom:(id)arg1;
- (void)onCreateVidyoRoom:(id)arg1;
- (void)onSendMessage:(id)arg1;
- (void)onMakeCallViaSIP:(id)arg1;
- (void)onMakeCallViaVidyo:(id)arg1;
- (void)onMsgFromAgent:(id)arg1;
- (void)LeaveConference:(id)arg1;
- (void)JoinConference:(id)arg1;
- (void)SendMessage:(id)arg1;
- (void)onMessageFromAgent:(id)arg1;
- (void)applicationWillEnterForeground;
- (void)applicationDidEnterBackground;
- (void)pluginInitialize;

@end

