//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage, ZBarReaderView, ZBarSymbolSet;

@protocol ZBarReaderViewDelegate <NSObject>
- (void)readerView:(ZBarReaderView *)arg1 didReadSymbols:(ZBarSymbolSet *)arg2 fromImage:(UIImage *)arg3;
@end

