//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

#import "ZBarReaderDelegate.h"
#import "ZBarReaderViewDelegate.h"

@class NSString, UIImagePickerController, ZBarReaderController, ZBarReaderViewController;

@interface ZBarCDVPlugin : CDVPlugin <ZBarReaderViewDelegate, ZBarReaderDelegate>
{
    ZBarReaderViewController *readerController;
    ZBarReaderController *imgPickerController;
    NSString *callbackId;
    UIImagePickerController *galleryBase64Picker;
    UIImagePickerController *cameraBase64Picker;
    _Bool _multiScan;
    UIImagePickerController *_galleryBase64Picker;
    UIImagePickerController *_cameraBase64Picker;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool multiScan; // @synthesize multiScan=_multiScan;
@property(retain, nonatomic) UIImagePickerController *cameraBase64Picker; // @synthesize cameraBase64Picker=_cameraBase64Picker;
@property(retain, nonatomic) UIImagePickerController *galleryBase64Picker; // @synthesize galleryBase64Picker=_galleryBase64Picker;
@property(retain, nonatomic) NSString *callbackId; // @synthesize callbackId;
@property(retain, nonatomic) ZBarReaderController *imgPickerController; // @synthesize imgPickerController;
@property(retain, nonatomic) ZBarReaderViewController *readerController; // @synthesize readerController;
- (_Bool)deviceHasFlashlight;
- (void)flashOff:(id)arg1;
- (void)flashOn:(id)arg1;
- (void)flashAvailable:(id)arg1;
- (id)imageResize:(id)arg1 andResizeTo:(struct CGSize)arg2;
- (id)platformString;
- (id)platform;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)readerControllerDidFailToRead:(id)arg1 withRetry:(_Bool)arg2;
- (void)dismissScannerView;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)adjustScannerQuality:(int)arg1;
- (void)showZbar:(id)arg1;
- (void)pauseZbar:(id)arg1;
- (void)stopZbar:(id)arg1;
- (void)showImagePicker:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

